### ISSUE TITLE
Transparent color over the header image

### ISSUE THREAD

**Issue by RoqueCampos** [florent37/MaterialViewPager#1]
Hi!

Please apologize my bad English.

Is there a way to have a full transparent color over the header image? When I use #00000000 as viewpager_color, there is a white overlay over the header image. I want to see the header image without overlay.

Thank you very much for this super library!

**Comment by florent37** [comment]
I see, the image has alpha 0.6, I give you a small fix

findViewById(R.id.materialviewpager_imageHeader).setAlpha(1)

Tell me if it's working

**Comment by vijayrawatsan** [comment]
@florent37 
Added pull request for the same. Please review and merge https://github.com/florent37/MaterialViewPager/pull/4

**Comment by florent37** [comment]
Yes, job done by @vijayrawatsan , thanks
