### ISSUE TITLE
Error: AppCompat does not support the current theme features

### ISSUE THREAD

**Issue by alburaawi** [florent37/MaterialViewPager#10]
Just tried your library and sample code and it's giving me the following error:
```java
AppCompat does not support the current theme features
```

I'm using ```targetSdkVersion 22``` so had to change ```ActionBarActivity``` to ```AppCompatActivity```.

Here is the full log report:
```java
05-06 04:43:27.346: E/AndroidRuntime(24499): FATAL EXCEPTION: main
05-06 04:43:27.346: E/AndroidRuntime(24499): Process: com.github.florent37.materialviewpager.sample, PID: 24499
05-06 04:43:27.346: E/AndroidRuntime(24499): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.florent37.materialviewpager.sample/com.github.florent37.materialviewpager.sample.MainActivity}: java.lang.IllegalArgumentException: AppCompat does not support the current theme features
05-06 04:43:27.346: E/AndroidRuntime(24499): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
05-06 04:43:27.346: E/AndroidRuntime(24499): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
05-06 04:43:27.346: E/AndroidRuntime(24499): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
05-06 04:43:27.346: E/AndroidRuntime(24499): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
05-06 04:43:27.346: E/AndroidRuntime(24499): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-06 04:43:27.346: E/AndroidRuntime(24499): 	at android.os.Looper.loop(Looper.java:135)
05-06 04:43:27.346: E/AndroidRuntime(24499): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
05-06 04:43:27.346: E/AndroidRuntime(24499): 	at java.lang.reflect.Method.invoke(Native Method)
05-06 04:43:27.346: E/AndroidRuntime(24499): 	at java.lang.reflect.Method.invoke(Method.java:372)
05-06 04:43:27.346: E/AndroidRuntime(24499): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
05-06 04:43:27.346: E/AndroidRuntime(24499): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
05-06 04:43:27.346: E/AndroidRuntime(24499): Caused by: java.lang.IllegalArgumentException: AppCompat does not support the current theme features
05-06 04:43:27.346: E/AndroidRuntime(24499): 	at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:360)
05-06 04:43:27.346: E/AndroidRuntime(24499): 	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:246)
05-06 04:43:27.346: E/AndroidRuntime(24499): 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
05-06 04:43:27.346: E/AndroidRuntime(24499): 	at com.github.florent37.materialviewpager.sample.MainActivity.onCreate(MainActivity.java:34)
05-06 04:43:27.346: E/AndroidRuntime(24499): 	at android.app.Activity.performCreate(Activity.java:5933)
05-06 04:43:27.346: E/AndroidRuntime(24499): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
05-06 04:43:27.346: E/AndroidRuntime(24499): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
05-06 04:43:27.346: E/AndroidRuntime(24499): 	... 10 more
````

**Comment by florent37** [comment]
as @ChrisBanes said in this stackoverflow thread http://stackoverflow.com/questions/29790070/upgraded-to-appcompat-v22-1-0-and-now-getting-illegalargumentexception-appcompa

Copy/Paste :

AppCompat is now more strict on what it expect in theme window flags, more closely matching what you would get from the framework.

The main reason behind this is to support Dialogs which we were also added in this release. They make heavy use of the windowNoTitle flag, which AppCompat previously didn't pay much attention to.

So to fix your issue you have two options:

The easy way is to just use Theme.AppCompat.NoActionBar as your parent theme. This will always do the right thing.

If you can't do that though (maybe you need to support action bar and no action bar), you should do the following:

	<style name="MyTheme" parent="Theme.AppCompat">
	    ...
	</style>

	<style name="MyTheme.NoActionBar">
	    
	    <item name="windowActionBar">false</item>
	    <item name="windowNoTitle">true</item>
	</style>

**Comment by florent37** [comment]
Tell me if it's not working ;)

**Comment by alburaawi** [comment]
Thanks mate.. this line did it:
```<item name="windowNoTitle">true</item>```

**Comment by alburaawi** [comment]
Quick question; 
I'm trying to pull info from a db using custom Adapter, but I keep getting the following error ```No adapter attached; skipping layout```.

I tried solutions suggested in the web such as [This] (http://stackoverflow.com/questions/28510578/no-adapter-attached-skipping-layout) but it goes blank and you can't see any of the ```CardView```

Any idea why I keep getting this error or what am I suppose to do to fix it? Thanks

**Comment by pmk2429** [comment]
I am trying to solve this problem but it doesnt seem to work for me.
I have styles.xml and v21/styles.xml.

My styles.xml looks like this:


    <style name="AppTheme" parent="Theme.AppCompat.NoActionBar"/>

        <style name="AppTheme.NoActionBar">
            <item name="colorPrimary">@color/colorPrimary</item>
            <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
            <item name="android:windowTranslucentStatus">true</item>

  

My v21/styles.xml looks like this  

    <style name="AppTheme" parent="Theme.AppCompat.NoActionBar">
            <item name="colorPrimary">@color/colorPrimary</item>
            <item name="colorPrimaryDark">@color/colorPrimaryDark</item>

            <item name="android:windowContentTransitions">true</item>
            <item name="android:windowAllowEnterTransitionOverlap">true</item>
            <item name="android:windowAllowReturnTransitionOverlap">true</item>
            <item name="android:windowSharedElementEnterTransition">@android:transition/move</item>
            <item name="android:windowSharedElementExitTransition">@android:transition/move</item>
            <item name="android:windowTranslucentStatus">true</item>

        </style>

  
  
Now I have created a BaseActivity in order to extend the Material NavDrawer in all the activities. In order to do so, it is required for me to first call the 

    setContentView(R.layout.activity_main);
        super.onCreate(savedInstanceState);

  

If I change this order then the activities which will extend the BaseACtivity wont be able to identify the controls in the BaseActivity and it gives me error for not able to find controls.

So it seems I am in deadlock.

Please let me know what to do.

Thanks in Advance.

**Comment by huyongqiang** [comment]
it work! Thx
