### ISSUE TITLE
Rapid scrolling results in varying Toolbar height

### ISSUE THREAD

**Issue by eatyoveshtables** [florent37/MaterialViewPager#11]
This is much more apparent on a Genymotion emulator than a device but is an issue on both.

![scroll_bug](https://cloud.githubusercontent.com/assets/6718711/7490782/0e001394-f401-11e4-8702-56ae796ccd43.gif)

**Comment by florent37** [comment]
Yes already noticed, but don't know where it can happens, maybe I missed to set a min&max value for tab-bar translation

**Comment by adamaviner** [comment]
Seems like the problem is in MaterialViewPagerAnimator.onMaterialScrolled
I added a pull request #13 with a fix

**Comment by florent37** [comment]
Hi, I fixed it & published 1.0.3 :+1:

**Comment by eatyoveshtables** [comment]
Awesome, I've checked it out and it seems to work perfectly for me now! Thanks for the quick response and fix!
