### ISSUE TITLE
how to change header logo for every tab?

### ISSUE THREAD

**Issue by srikanthnama** [florent37/MaterialViewPager#111]
hi i am new to android and trying to create an application like google news let  and i completed app with the help of your library and now i am trying to change header logo for every tab with animation or without animation  like play newsstand can you help me for this .

**Comment by florent37** [comment]
you can do it from the setMaterialViewPagerListener

	ImageView headerLogo = (ImageView)findViewById(R.id.myLogo);

	mViewPager.setMaterialViewPagerListener(new MaterialViewPager.Listener() {
	            @Override
	            public HeaderDesign getHeaderDesign(int page) {
	                switch (page) {
	                    case 0:
	                    	headerLogo.setDrawable(myDrawable1);
	                        return HeaderDesign.fromColorResAndUrl(
	                                R.color.green,
	                                "https://fs01.androidpit.info/a/63/0e/android-l-wallpapers-630ea6-h900.jpg");
	                    case 1:
	                    	headerLogo.setDrawable(myDrawable2);
	                        return HeaderDesign.fromColorResAndUrl(
	                                R.color.blue,
	                                "http://cdn1.tnwcdn.com/wp-content/blogs.dir/1/files/2014/06/wallpaper_51.jpg");
	                    case 2:
	                    	headerLogo.setDrawable(myDrawable3);
	                        return HeaderDesign.fromColorResAndUrl(
	                                R.color.cyan,
	                                "http://www.droid-life.com/wp-content/uploads/2014/10/lollipop-wallpapers10.jpg");
	                    case 3:
	                    	headerLogo.setDrawable(myDrawable4);
	                        return HeaderDesign.fromColorResAndUrl(
	                                R.color.red,
	                                "http://www.tothemobile.com/wp-content/uploads/2014/07/original.jpg");
	                }

	                //execute others actions if needed (ex : modify your header logo)

	                return null;
	            }
	        });

**Comment by florent37** [comment]
look at the headerLogo.setDrawable(myDrawable1);

**Comment by meunicorn** [comment]
well while i change the viewpager,and the header logo change,too . and if i want to add a scale animation like google newsstand.could you please tell me how to do it?

**Comment by vaikunj123** [comment]
How to  left side arrow  remove in toolbar??
& how to custom toolbar in main matrialview viewpager
