### ISSUE TITLE
Still can't attach a OnClickListener to the top picture

### ISSUE THREAD

**Issue by MarKco** [florent37/MaterialViewPager#114]
Hello Florent,
the previous issue with the same topic was closed but actually it's not (https://github.com/florent37/MaterialViewPager/issues/62). I'd still like to attach a ClickListener on the MaterialViewPager header picture, in order to start a gallery activity or anything else, but I couldn't find a way to do so. Is this already possible in this version? Theoretically it'd be enough to be able to retrieve the View and then attaching the listener to it, isn't it?

I tried by adding

findViewById(R.id.materialviewpager_imageHeader).setOnClickListener(new View.OnclickListener(){
    public void onClick(View v){

    }
});

but it never gets triggered, it seems to me that there's some layout above it preventing the onClick event to be triggered on the picture.

I guess it's pretty common to be willing to attach a clickListener to the picture, mainly in order to start a galleryActivity: I guess I'm not the only one out there who'd like to be able to do so. I'm obviously willing to help if I can.

Cheers

P.S. I already updated to 1.0.8

**Comment by hongzhou85** [comment]
How about you insert a custom header and you could set "onClickListener" from there?

**Comment by MarKco** [comment]
Hello ongzhou85,
that sounded like a good idea, so I tried. I created a custom layout and put a picture in it, trying to attach a OnClickListener to the picture and to the layout itself. Alas, it's not triggered. I'm pretty sure there's a layout that covers the header and prevents the touch event to be triggered properly: that's why I don't know how to solve this issue, because I think that covering layout is something needed by the library itself.

**Comment by MarKco** [comment]
I recorded a screencast: you can't see that I clicked on the header but you can see nothing happens (a Toast should appear) https://www.youtube.com/watch?v=M_gG2EE1krs

**Comment by hongzhou85** [comment]
I tried a custom header with image and buttons in it and the button is able to detect event. So in the layout, I specified the pager_logo attributes to a custom layout. and in the codes, just fetch the button views using Button btn = (Button)findViewById(R.id.mybutton). Then add a listener. btn.setOnClickListener( ... ). This should works.

<com.github.florent37.materialviewpager.MaterialViewPager
        android:id="@+id/pager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginBottom="48dp"
        app:viewpager_logo="@layout/fragment_mycustom_header"
        app:viewpager_pagerTitleStrip="@layout/mylayout_tab"
        app:viewpager_logoMarginTop="0dp"
        app:viewpager_color="@color/white"
        app:viewpager_headerHeight="165dp"
        app:viewpager_headerAlpha="1.0"
        app:viewpager_hideLogoWithFade="true"
        app:viewpager_hideToolbarAndTitle="true"
        app:viewpager_enableToolbarElevation="true"
        app:viewpager_parallaxHeaderFactor="0.5"
        app:viewpager_headerAdditionalHeight="5dp"
        app:viewpager_displayToolbarWhenSwipe="false"/>

![screenshot_2015-07-24-23-18-58](https://cloud.githubusercontent.com/assets/4978166/8877904/b9289286-325a-11e5-8207-eee1614a56b9.png)

**Comment by florent37** [comment]
Hi, Yes I already seen it, but the top view is behind the recyclerview, If anyone has a small trick, I'll be happy to use it

**Comment by florent37** [comment]
should be fix on the '1.1.0', can you try ?

sorry for this issue :'(
