### ISSUE TITLE
mHeader color flickering while swiping tabs

### ISSUE THREAD

**Issue by trajakovic** [florent37/MaterialViewPager#117]
Hy there, demo is here: [Header color flickering](https://www.flickr.com/photos/51321609@N03/shares/Jos983)

I believe that flicker occurs when ValueAnimator starts animation since interpolation is starting with settings.color that is not current color of header.

Probable fix is to move
```
//set the new color as MaterialViewPager's color
this.settings.color = color;
```

inside updateListener of Animator.

**Comment by florent37** [comment]
thanks :)
