### ISSUE TITLE
If ViewPager is initialized with setCurrentItem(0) then header won't refresh

### ISSUE THREAD

**Issue by inmyth** [florent37/MaterialViewPager#120]
If viewpager is initialized with current item set with the first item:
````java
mViewPager.getViewPager().setCurrentItem(0);
````
or just remove that line, then header's listener won't trigger. In other word the first page's header will not refresh its color or image either from url or resources, at least for the first time. The demo sample is using the second item or setCurrentItem(1). 
I seem to remember that the default listener for Android ViewPager is OnPageChangeListener which is only triggered if the page is changed. I assume Material View Pager is deriving the listener from it. 
For this I found one work around which is super ugly. Basically do two setCurrentItem in sequence 
````java
mViewPager.getViewPager().setCurrentItem(1);
mViewPager.getViewPager().setCurrentItem(0);
````

**Comment by florent37** [comment]
please look at https://github.com/florent37/MaterialViewPager/issues/122
