### ISSUE TITLE
OnRotation with Fragments - toolbar losses properties

### ISSUE THREAD

**Issue by Ashok-Varma** [florent37/MaterialViewPager#121]
My Activity code:

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_movie_details_news_stand);
        setTitle("");

        mViewPager = (MaterialViewPager) findViewById(R.id.materialViewPager);

        toolbar = mViewPager.getToolbar();
        mDrawer = (DrawerLayout) findViewById(R.id.drawerLayout);

        if (toolbar != null) {
            setSupportActionBar(toolbar);

            final ActionBar actionBar = getSupportActionBar();
            if (actionBar != null) {
                actionBar.setDisplayHomeAsUpEnabled(true);
                actionBar.setDisplayShowHomeEnabled(true);
                actionBar.setDisplayShowTitleEnabled(true);
                actionBar.setDisplayUseLogoEnabled(false);
                actionBar.setHomeButtonEnabled(true);
            }
        }

        DrawerFragment drawerFragment = (DrawerFragment) getSupportFragmentManager().findFragmentById(R.id.drawerFragment);
        drawerFragment.setUp(mDrawer, toolbar);

        volleySingleton = VolleySingleton.getInstance();
        requestQueue = volleySingleton.getRequestQueue();

        long movieID = getIntent().getLongExtra(INTENT_EXTRA_MOVIE_ID, 1);
        String title = getIntent().getStringExtra(INTENT_EXTRA_MOVIE_TITLE);

        generateFragments();

        mViewPager.getViewPager().setAdapter(new movieDetailsPagerAdapter(getSupportFragmentManager()));

        if (savedInstanceState != null) {
            movieDetails = savedInstanceState.getParcelable(STATE_MOVIE_DETAILS);

            if (movieDetails.server_timezone != null && !movieDetails.server_timezone.equals("N/A")) {
               mViewPager.setMaterialViewPagerListener(new MovieMaterialViewPagerListener());
            } else {
                sendJsonRequest(URLModifierclass.getMovieDetailsByIDURL(movieID, true, true));
                mViewPager.setMaterialViewPagerListener(new DefaultMaterialViewPagerListener());
            }
        } else {
            sendJsonRequest(URLModifierclass.getMovieDetailsByIDURL(movieID, true, true));
            mViewPager.setMaterialViewPagerListener(new DefaultMaterialViewPagerListener());
        }

        mViewPager.getViewPager().setOffscreenPageLimit(mViewPager.getViewPager().getAdapter().getCount());
        mViewPager.getPagerTitleStrip().setViewPager(mViewPager.getViewPager());

        View view = mViewPager.getRootView();
        TextView headerLogo = (TextView) view.findViewById(R.id.logo_white);
        headerLogo.setText(title);

        mViewPager.getViewPager().setCurrentItem(1);

    }

Everything works fine, if i open normally. But if i rotate the screen once. From then it shows all the below problems, even if i come to portriat. so when saveninstancestate!=null it fails.

The Problems
1) it sets the title but the title is above statusbar. I can see character tails in statusbar
2) I made viewpager_transparentToolbar="false" but that is transparent
3) It doesn't set currentItem as 1

All these occur from first time i rotate the screen

Try 1 : :+1: 
i tried moving if block top the end of oncreate but still all problems exist

Try 2: :+1: 
i tried removing everything from if block except retrieving my object still it fails

Any Idea? Should i need to do some thing in onSavedInstanceState() ??

**Comment by Ashok-Varma** [comment]
I removed onSavedInstanceState() completely and also removed the if block from on activity created. Still the problem occurs.
 
Same problem occurs even if i change the font size in settings and come back to activity

**Comment by Ashok-Varma** [comment]
Regarding Issue #122 

@florent37  can you add

It will be good if we can manually trigger the Update of image.
I mean if we want to change the image during runtime. We can change it by changing listener but it won't update the current image without us swiping to other tab.
I we had a method which when we call it will refresh the listener then it will be really good.

**Comment by florent37** [comment]
can you try with the 1.1.0 ?

**Comment by florent37** [comment]
@Ashok-Varma like materialViewPager.notifyHeaderChanged() ?

**Comment by florent37** [comment]
@Ashok-Varma I updated the 1.1.0 to add it :) look at my sample

Thanks for the idea :+1: 

logo.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    mViewPager.notifyHeaderChanged();
                    Toast.makeText(getApplicationContext(), "Yes, the title is clickable", Toast.LENGTH_SHORT).show();
                }
            });

**Comment by Ashok-Varma** [comment]
@florent37 
I can't find the method i tried rebuilding gradle many times. I think you haven't added that change to gradle. So i downloaded the zip and used it Thankyou VeryMuch
And 1.1.0 solved the rotation framents error thankyou very much

**Comment by florent37** [comment]
clear your gradle cache
cd $HOME/.gradle/caches/modules-2/files-2.1/com.github.florent37
rm -rf carpaccio/

**Comment by Ashok-Varma** [comment]
did it but didn't worked then.
Before yesterday i changed OS windows-10 clean install.
Then it came. :p

Thankyou verymuch i will release my app soon credits to you.
