### ISSUE TITLE
Image show only on swipe?

### ISSUE THREAD

**Issue by LinkOut** [florent37/MaterialViewPager#122]
Why image is showing only if i swipe or change fragment?

**Comment by RodrigezJson** [comment]
same goes to me. please take action immediately friend :). i think it was a bugs

**Comment by Ashok-Varma** [comment]
It will be good if we can manually trigger the Update of image.
I mean if we want to change the image during runtime.  We can change it by changing listener but it won't update the current image without us swiping to other tab.
I we had a method which when we call it will refresh the listener then it will be really good.

**Comment by LinkOut** [comment]
Yep, i'd like have a method that refresh the listener too. It's annoying not to see the image on the top.

Thanks

**Comment by RodrigezJson** [comment]
ya i am very sure that most of us got the same problem here.

**Comment by inmyth** [comment]
this is basically the same problem as this
https://github.com/florent37/MaterialViewPager/issues/120

**Comment by florent37** [comment]
oooooo I see problem, if you look at MaterialViewPager, the attribute lastPosition is initialised at 0, so the header wont't refresh.
I'm sorry, I update a quick fix for you guys !

**Comment by RodrigezJson** [comment]
Ok thanks a lot dude. U doing the great job. :)

**Comment by florent37** [comment]
I look for issues today, I didn't have the time...

**Comment by RodrigezJson** [comment]
Ok. Cant wait for your update. Thanks again

**Comment by Ashok-Varma** [comment]
@florent37  Thankyou for that
this issue #121 behaves strange can you please check it

**Comment by florent37** [comment]
yes. OnRotation with fragments is very strange, I'll do it after the small fixes

**Comment by Ashok-Varma** [comment]
@florent37  you are doing great Job. You saved me lot of time. Thankyou VeryMuch

**Comment by florent37** [comment]
you can try the '1.1.0', it contain the fix for the header :+1:

**Comment by RodrigezJson** [comment]
Nice job man

**Comment by Ashok-Varma** [comment]
@florent37  can you add

It will be good if we can manually trigger the Update of image.
I mean if we want to change the image during runtime. We can change it by changing listener but it won't update the current image without us swiping to other tab.
I we had a method which when we call it will refresh the listener then it will be really good.

**Comment by LinkOut** [comment]
@florent37 Thanks for the fix.
