### ISSUE TITLE
recyclerview with gridlayout manager(2 col) is breaking design .h

### ISSUE THREAD

**Issue by nowfalsalahudeen** [florent37/MaterialViewPager#124]
any way to fix it.. am totally stucked at this part..plz help me
![error](https://cloud.githubusercontent.com/assets/4261741/9020869/a224ce26-3843-11e5-9e4d-d906a4be3f87.jpg)

**Comment by florent37** [comment]
Hi, it's pretty easy to fix  : (with 2 colums)

        mAdapter = new RecyclerViewMaterialAdapter(YOUR_ADAPTER, 2 );
        mRecyclerView.setAdapter(mAdapter);
