### ISSUE TITLE
new to Git hub

### ISSUE THREAD

**Issue by Rahulkishanm** [florent37/MaterialViewPager#135]
im new to Github,i want to use this MaterialView pager material design into my project i tryd to import it into android studio,but it shows some error

**Comment by devkhan** [comment]
Please provide more info about your problem. How are you importing the library? What is the error? etc.

No body will be able to help you without any information.

:+1:

**Comment by Rahulkishanm** [comment]
I'm using android studio
I imported​ the MaterialViewPager-master by
  file->new->import project
and the error shown is
Gradle DSL method not found:'android()'
possible causes:
Error:(39, 0) Gradle DSL method not found: 'android()'
Possible causes:<ul><li>The project 'MaterialViewPager-master' may be using
a version of Gradle that does not contain the method.
The build file may be missing a Gradle plugin.


On Tue, Aug 11, 2015 at 4:48 PM, Devesh Khandelwal <notifications@github.com

**Comment by devkhan** [comment]
There is no need to do that. Just add the following to your build.gradle(:app) file:

    compile ('com.github.florent37:materialviewpager:1.1.0@aar'){
        transitive = true
    }

And then perform a Gradle sync. The library should be automatically added to your project.

You can now use the import statements. :smiley:

**Comment by Rahulkishanm** [comment]
1)i downloaded MaterialViewPager-master.
2)file->new->import project //i have a doubt weather should import as module or project 
3)in the MaterialViewPager-master there was build.gradle i pasted 
  compile ('com.github.florent37:materialviewpager:1.1.0@aar'){
        transitive = true
    }
4)i performed a Gradle sync
5)i get an error Error:(3, 0) Cannot invoke method compile() on null object
![image](https://cloud.githubusercontent.com/assets/11585684/9242624/fab3690a-41a1-11e5-8486-7cddaeb18b81.png)

**Comment by devkhan** [comment]
I think you are not getting my point. **You do not need to import the project**. Just add what I told you above in the gradle build file of your app, **NOT MaterialViewPager**, and you'll be good to go.

**Comment by Rahulkishanm** [comment]
Thank you again sir,but here comes an another error,plz give me step by step process so it will be usefull
![image](https://cloud.githubusercontent.com/assets/11585684/9245515/52b4b710-41c2-11e5-8e8e-aac38842904d.png)

**Comment by devkhan** [comment]
You are going in the right direction. Tell me the error, the error is not visible in the snapshot. :+1:

**Comment by Rahulkishanm** [comment]
Thank you again sir,but here comes an another error,plz give me step by step process so it will be usefull
1)i created anew project
2)i imported d module 
3)in bulid i inserted
compile ('com.github.florent37:materialviewpager:1.1.0@aar'){
    transitive = true
}
![image](https://cloud.githubusercontent.com/assets/11585684/9245630/495d3eac-41c3-11e5-8661-88790b49ca70.png)

**Comment by Rahulkishanm** [comment]
Thank you again sir,but here comes an another error,plz give me step by step process so it will be usefull
1)i created anew project
2)i imported d module 
3)in bulid i inserted
compile ('com.github.florent37:materialviewpager:1.1.0@aar'){
    transitive = true
}
![image](https://cloud.githubusercontent.com/assets/11585684/9245630/495d3eac-41c3-11e5-8661-88790b49ca70.png)

**Comment by devkhan** [comment]
Well, it should work as now you've done the right steps. Can you please, put up your project on a repo, so I can compile myself?

**Comment by Rahulkishanm** [comment]
actually sir im new to git hub i have created a repo but how to add my project,https://github.com/Rahulkishanm/celebrationsapp buti doono how to insert my project into it

**Comment by Rahulkishanm** [comment]
https://gist.github.com/Rahulkishanm/3f2c929b8c904a5a60f9

**Comment by devkhan** [comment]
I can't run your app like this, you have to push your app into a **repository**, not a **gist**.

I have seen that you have created a repo in your account, now you just need to push your app's code into that repository.

**Comment by Rahulkishanm** [comment]
I don't know how to ad my project into my repo​..
I know to store it in drive and share my link

On Thu, Aug 13, 2015 at 2:44 PM, Devesh Khandelwal <notifications@github.com

**Comment by Rahulkishanm** [comment]
https://drive.google.com/folderview?id=0B1WFXRJ-fFkcfmNFOW5TZzhOQUlGd2RUd082LXpzRUk5WTczT2FyUmJkc1N5QkRjck5pbTA&usp=sharing
this is my project....imm new to git hub so I don't know how to add into
repo...plz share me some knowledge​

On Thu, Aug 13, 2015 at 3:13 PM, Rahul kishan <rahulkishan02081995@gmail.com
> wrote:

> I don't know how to ad my project into my repo​..
> I know to store it in drive and share my link
>
> On Thu, Aug 13, 2015 at 2:44 PM, Devesh Khandelwal <

**Comment by devkhan** [comment]
Found the error, there is comma [,], in your project's build.gradle, right after classpath statements. Remove the comma and it should sync properly.

**Comment by devkhan** [comment]
@Rahulkishanm If your issue is resolved, then please close this issue.

Thank You.

**Comment by Rahulkishanm** [comment]
sir it dint wrk...plz provide me step by step process sir

On Fri, Aug 14, 2015 at 2:25 PM, Devesh Khandelwal <notifications@github.com

**Comment by devkhan** [comment]
Did you try removing that **comma [ , ]** I mentioned about in your **Celebrations** project?

**Comment by Rahulkishanm** [comment]
Error:(3, 0) Cannot invoke method compile() on null object
![image](https://cloud.githubusercontent.com/assets/11585684/9280341/405940c6-42db-11e5-9475-52ac6dcf404f.png)

**Comment by devkhan** [comment]
Long discussions are not good for here. Can you please join [Gitter](http://gitter.im/), so that I can help you in detail?
