### ISSUE TITLE
Header animation dosent'work

### ISSUE THREAD

**Issue by UFreedom** [florent37/MaterialViewPager#14]
Hi, I added a MaterialViewPager in one Fragment, and for the first time, all worked well, Header scrolled together with RecylerView.But so wierd that for the second time，RecyclerView scrolled without Header anymore。

![Gif](http://img1.ph.126.net/eZN2JyvI9ZzfzWzPi5hZqg==/6630454238210994202.gif)

**Comment by florent37** [comment]
thank you to have noticed this bug. 
I think it's on the MaterialViewPagerHelper / hashMap we can found the solution :+1:

**Comment by UFreedom** [comment]
Hello,Have you fixes the bug? or what I can do to test it？

**Comment by florent37** [comment]
Yes I just fixed it

can you try to import the 1.0.2.3 ?

and please tell me if it works :)

    compile ('com.github.florent37:materialviewpager:1.0.2.3@aar'){
        transitive = true
    }

**Comment by florent37** [comment]
it's included in **1.0.3**

**Comment by UFreedom** [comment]
Awesome！It works well !,Thanks for good library！:)

**Comment by florent37** [comment]
thanks for reporting bugs :+1: 
This help us improve this library :smile:
