### ISSUE TITLE
Using StaggeredGridLayoutManager with 2+ columns

### ISSUE THREAD

**Issue by tl-nguyen** [florent37/MaterialViewPager#141]
Hello, i'm trying to use the recyclerview with StaggeredGridLayoutManager, but the whole design breaks after that, is there anyway to fix this problem ?

**Comment by krzysiek-icomapss** [comment]
Use not default adapter:
mAdapter = new RecyclerViewMaterialAdapter(new TestRecyclerViewAdapter(mContentItems),elementsCount);

**Comment by tl-nguyen** [comment]
Thanks for the answer. And yes, I'm aware of the RecyclerViewMaterialAdapter. The problem is where i set the layoutmanager type: 

```
@Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        mRecyclerView = (RecyclerView) view.findViewById(R.id.recyclerView);
        RecyclerView.LayoutManager layoutManager = new StaggeredGridLayoutManager(2, StaggeredGridLayoutManager.VERTICAL);
        mRecyclerView.setLayoutManager(layoutManager);
        mRecyclerView.setHasFixedSize(true);

        mAdapter = new RecyclerViewMaterialAdapter(new TestRecyclerViewAdapter(mContentItems));
        mRecyclerView.setAdapter(mAdapter);

        {
            for (int i = 0; i < ITEM_COUNT; ++i)
                mContentItems.add(new Object());
            mAdapter.notifyDataSetChanged();
        }

        MaterialViewPagerHelper.registerRecyclerView(getActivity(), mRecyclerView, null);
    }

```

I use StaggeredGridLayoutManager(2, StaggeredGridLayoutManager.VERTICAL); instead of LinearLayoutManager. And the second column start at the top of the screen and it covers the whole app-bar. Is there any way i can fix this? Thanks in advance

**Comment by krzysiek-icomapss** [comment]
Look at code:
 mAdapter = new RecyclerViewMaterialAdapter(new TestRecyclerViewAdapter(mContentItems),elementsCount);

u have second argument in constructor of RecyclerViewMaterialAdapter just use it and set number of items in grid row. The same number which is used in 
RecyclerView.LayoutManager layoutManager = new StaggeredGridLayoutManager(2, StaggeredGridLayoutManager.VERTICAL);

**Comment by tl-nguyen** [comment]
Omg, stupid me, thanks a lot man
