### ISSUE TITLE
Showing a fragment without a RecyclerView

### ISSUE THREAD

**Issue by euri16** [florent37/MaterialViewPager#146]
Can I show a single Item (Like just one card of any manually placed info) instead of having a RecyclerView. When I try to do it my fragment overlays the MaterialViewPager.

**Comment by xesun** [comment]
RecyclerViewMaterialAdapter adapter = new RecyclerViewMaterialAdapter(yourAdapter);
recyclerView.setAdapter(adapter);

**Comment by florent37** [comment]
If you want to display a fragment without a recyclerview, you shoul embed the content in an ObservableScrollView, and put in the top a *material_view_pager_placeholder*, like my sample 

https://github.com/florent37/MaterialViewPager/blob/master/sample/src/main/res/layout/fragment_scroll.xml

    <com.github.ksoichiro.android.observablescrollview.ObservableScrollView
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/scrollView"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <include layout="@layout/material_view_pager_placeholder"/>
   
           YOUR CONTENT

**Comment by Alchimehd** [comment]
Hello,

Could you please leave advanced details. Should the fragmentPagerAdapter return An ObservableScrollView ?

Thank you

**Comment by softmarshmallow** [comment]
@Alchimehd did you found any details?

**Comment by Alchimehd** [comment]
@softmarshmallow I'm sorry but I don't even remember the project I was working on...
