### ISSUE TITLE
Display error: Apply RecyclerViewFragment with GridLayoutManager

### ISSUE THREAD

**Issue by waitray** [florent37/MaterialViewPager#147]
@florent37,when i applying RecyclerViewFragment with GridLayoutManager, it display just cover the tab.u can see the picture below. but when i apply  RecyclerViewFragment with LinearLayoutManager, it goes well. 

any help?

![image](https://cloud.githubusercontent.com/assets/6244407/9378522/bc2c457c-4754-11e5-8d15-3d8c4bfd1445.png)

![image](https://cloud.githubusercontent.com/assets/6244407/9378617/693b43a8-4755-11e5-8ce2-b5076c3d6013.png)
here is my code:

   @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        mRecyclerView = (RecyclerView) view.findViewById(R.id.recyclerView);
        RecyclerView.LayoutManager layoutManager = new GridLayoutManager(getActivity(),3);
        mRecyclerView.setLayoutManager(layoutManager);
        mRecyclerView.setHasFixedSize(true);

        mAdapter = new RecyclerViewMaterialAdapter(new TestRecyclerViewAdapter(mContentItems,getActivity()));
        mRecyclerView.setAdapter(mAdapter);

        {
            for (int i = 0; i < ITEM_COUNT; ++i)
                mContentItems.add(String.valueOf(i));
            mAdapter.notifyDataSetChanged();
        }

        MaterialViewPagerHelper.registerRecyclerView(getActivity(), mRecyclerView, null);
    }

public class TestRecyclerViewAdapter extends RecyclerView.Adapter<RecyclerView.ViewHolder> {

    List<Object> contents;

    static final int TYPE_HEADER = 0;
    static final int TYPE_CELL = 1;

    static Context context;

    public static class ViewHolder extends RecyclerView.ViewHolder {
        // each data item is just a string in this case
        protected TextView mTextView;
        protected ImageView mImageView;

        public ViewHolder(View v) {
            super(v);
            mTextView = (TextView) v.findViewById(R.id.card_view_text);
            mImageView = (ImageView)v.findViewById(R.id.card_view_img);
        }
    }

    public TestRecyclerViewAdapter(List<Object> contents,final Context _context) {
        this.contents = contents;
        context = _context;
    }

    @Override
    public int getItemViewType(int position) {
        switch (position) {
            case 0:
                return TYPE_HEADER;
            default:
                return TYPE_CELL;
        }
    }

    @Override
    public int getItemCount() {
        return contents.size();
    }

    @Override
    public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View view ;
        switch (viewType) {
            case TYPE_HEADER: {
                Log.d("type:",TYPE_HEADER+"TYPE_HEADER");
                view = LayoutInflater.from(parent.getContext())
                        .inflate(R.layout.list_item_card_small, parent, false);
                view.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        Toast.makeText(context,"标题",Toast.LENGTH_LONG).show();
                    }
                });
                return new ViewHolder(view);
            }
            case TYPE_CELL: {
                view = LayoutInflater.from(parent.getContext())
                        .inflate(R.layout.list_item_card_small, parent, false);
                view.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        Toast.makeText(context,"内容",Toast.LENGTH_LONG).show();
                    }
                });
                return new ViewHolder(view);
            }
        }
        return null;
    }

    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
        switch (getItemViewType(position)) {
            case TYPE_HEADER:
                Log.d("type bind:", TYPE_HEADER + "TYPE_HEADER");
                ((ViewHolder)holder).mTextView.setText("表头");
                break;
            case TYPE_CELL:
                StringBuilder sb = new StringBuilder();
                sb.append("表身").append(position).append(":").append(contents.get(position));
                ((ViewHolder) holder).mTextView.setText(sb);
                break;
        }
    }
}

//list_item_card_small.xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <android.support.v7.widget.CardView
        android:id="@+id/card_view"
        android:layout_width="match_parent"
        android:layout_height="80dp"
        android:layout_marginBottom="@dimen/cardMarginVertical"
        android:layout_marginLeft="@dimen/cardMarginHorizontal"
        android:layout_marginRight="@dimen/cardMarginHorizontal"
        android:layout_marginTop="@dimen/cardMarginVertical"
        app:cardCornerRadius="2dp"
        app:cardElevation="2dp"
        app:cardPreventCornerOverlap="false"
        app:contentPadding="0dp">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">
            <TextView
                android:layout_gravity="center|left"
                android:id="@+id/card_view_text"
                android:layout_width="wrap_content"
                android:layout_height="match_parent" />
            <ImageView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center|right"
                android:src="@drawable/flying"
                android:id="@+id/card_view_img"
                />
        </LinearLayout>
    </android.support.v7.widget.CardView>
</FrameLayout>

**Comment by krzysiek-icomapss** [comment]
pls check other issues there was one similar

**Comment by florent37** [comment]
You have to indicate the number of cells per line in the RecyclerViewMaterialAdapter
as below : NUMBER_OF_CELL_PER_LINE

and it should be fine :+1: 

          mAdapter = new RecyclerViewMaterialAdapter(new TestRecyclerViewAdapter(mContentItems,getActivity()),NUMBER_OF_CELL_PER_LINE);

**Comment by waitray** [comment]
Thank you all!

2015-08-26 15:52 GMT+08:00 Florent CHAMPIGNY <notifications@github.com>:
