### ISSUE TITLE
Memory leak in MaterialViewPagerHelper

### ISSUE THREAD

**Issue by MGaetan89** [florent37/MaterialViewPager#15]
I started using https://github.com/square/leakcanary to find potential memory leaks in my application.

Turns out there is one in your great library in [MaterialViewPagerHelper](https://github.com/florent37/MaterialViewPager/blob/master/materialviewpager/src/main/java/com/github/florent37/materialviewpager/MaterialViewPagerHelper.java#L28). Indeed, it holds a static `HashMap` that is never cleared. Maybe you could add a method to clear the content of that map when the `Activity`/`Fragment` is destroyed?

**Comment by florent37** [comment]
Yes, I thinks it would be usefull.

Do you want to do in and send a pull request ?

if not I will do it myself, just to prevent doing same work twite

**Comment by MGaetan89** [comment]
I can't work on this for the next two weeks.
I can have a look then if you haven't fixed it yet.

**Comment by florent37** [comment]
I fixed it in **1.0.3.1** can you check please ? :)

**Comment by florent37** [comment]
**MaterialViewPager.java**
    @Override
    protected void onDetachedFromWindow() {
        MaterialViewPagerHelper.unregister(getContext());
        super.onDetachedFromWindow();
    }

**MaterialViewPagerHelper.java**
    public static void unregister(Context context) {
        if(context != null)
            hashMap.remove(context);
    }

**Comment by MGaetan89** [comment]
It looks like there is no issue now.
Thanks for the quick fix :smile:

**Comment by florent37** [comment]
Thanks for your reporting :+1:
