### ISSUE TITLE
layout probleam

### ISSUE THREAD

**Issue by jiqimaogou** [florent37/MaterialViewPager#160]
in material_view_pager_layout.xml, the viewpager is

    <android.support.v4.view.ViewPager
        android:id="@+id/viewPager"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

wrapped with releative layout

![qq 20150906132927](https://cloud.githubusercontent.com/assets/1407040/9702649/3c33cde6-549b-11e5-9db7-fba4e2a2b2b4.png)

and the viewpager content is on top of the header.

**Comment by florent37** [comment]
what's your content ? recyclerview or scrollview ?

if scroll, please add the  <include layout="@layout/material_view_pager_placeholder"/>

if recycler, please use the RecyclerViewMaterialAdapter
