### ISSUE TITLE
Sometimes on scrolling, the header and strip becomes transparent and sometimes on tab change strip becomes transparent !

### ISSUE THREAD

**Issue by nikhilverma1395** [florent37/MaterialViewPager#162]
![screenshot_2015-09-14-13-39-55](https://cloud.githubusercontent.com/assets/9127344/9845170/af29db78-5ae6-11e5-9aae-3307a214dd44.png)

See the random padding gap in this image.

![screenshot_2015-09-14-13-40-24](https://cloud.githubusercontent.com/assets/9127344/9845189/d07c38f2-5ae6-11e5-9962-17e0a10d49c4.png)

See the random padding gap in this image.

![screenshot_2015-09-14-13-40-58](https://cloud.githubusercontent.com/assets/9127344/9845208/ef46a4f2-5ae6-11e5-9d16-0dcb5ec9358c.png)
 
Sometimes the header becomes transparent and the below scrolled list is visible.

![screenshot_2015-09-14-13-41-10](https://cloud.githubusercontent.com/assets/9127344/9845222/09187662-5ae7-11e5-9022-45bb320e1c4c.png)

Same issue !

Thanks!

**Comment by dimitrisCBR** [comment]
I just bumped on the same issue today. How did you solve it?

**Comment by nikhilverma1395** [comment]
Nope 🙀

**Comment by enginebai** [comment]
Same issue. Does anyone have a solution?

**Comment by karanschhabra** [comment]
same issue :/ @florent37  kindly help  :)

**Comment by scallacs** [comment]
Same issue...

**Comment by thomasdsouza** [comment]
+1

**Comment by nuhkoca** [comment]
+1

**Comment by antoxa2584x** [comment]
+1

**Comment by nuhkoca** [comment]
@florent37 do you hear us? Please release a new update to fix that bug
