### ISSUE TITLE
RecyclerView doesn't look fine with Grid Layout Manager !

### ISSUE THREAD

**Issue by vj-1023** [florent37/MaterialViewPager#179]
@florent37 

Recycler View was working fine till used with Linear Layout Manager works fine.
But when i used Grid Layout Manager !
This happened 
![image](https://cloud.githubusercontent.com/assets/12961547/10755476/fe26c9f8-7cc3-11e5-87cd-7a8fc646e78b.png)      

The complete fragment shifted up 
and the first item of the grid view is appearing blank

**Comment by Ashok-Varma** [comment]
yes this bug was fixed previously i guess. which update are you using ??

**Comment by Mithrandir21** [comment]
I had the exact same issue and after implementing the recommended constructor (with NUMBER_OF_CELL_PER_LINE), the issue was resolved.

I suggest closing this issue as the recommended alteration corrects the issue.

**Comment by Ashok-Varma** [comment]
@florent37 yeah we can close this

**Comment by ArsalRaza** [comment]
I also have the same problem but it resolved now, thanks guys...!

**Comment by BAYEGASPARD** [comment]
Hi ArasalRaza,
Could you please give me the method to use.

*Regards,*

*Baye Gaspard,*

*Co-founder of katambatech*

*Web: **www.katambatech.com* <http://www.katambatech.com/>

*Email: **katambatech@gmail.com* <katambatech@gmail.com>

*Contact: **+237 650968061* <%2B237%20650968061>* / 693720691*

**Comment by Ashok-Varma** [comment]
@BAYEGASPARD 

this is the adapter constructor that you should be using

```java
mAdapter = new RecyclerViewMaterialAdapter(new TestRecyclerViewAdapter(mContentItems,getActivity()),NUMBER_OF_CELL_PER_LINE);
```

**Comment by BAYEGASPARD** [comment]
Thank you Ashok Varma.Will try that out.Have a blessed day.



*Regards,*

*Baye Gaspard,*

*Co-founder of katambatech*

*Web: **www.katambatech.com* <http://www.katambatech.com/>

*Email: **katambatech@gmail.com* <katambatech@gmail.com>

*Contact: **+237 650968061* <%2B237%20650968061>* / 693720691*

**Comment by SadraxKasCic** [comment]
thanks for the answers. It help me. I have also a problem with searchView with materialViewPager. in suggestion??? please
