### ISSUE TITLE
view pager still thinks it has a toolbar even though toolbar is disabled

### ISSUE THREAD

**Issue by osiloke** [florent37/MaterialViewPager#186]
In relation to @IlyaEremin comments on #108  (i think, i can see your image). When view pager is configured as such
`
<com.github.florent37.materialviewpager.MaterialViewPager
        android:background="@color/md_grey_100"
        android:id="@+id/materialViewPager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:viewpager_hideLogoWithFade="true"
        app:viewpager_hideToolbarAndTitle="true"
        app:viewpager_disableToolbar="true"
        app:viewpager_logo="@layout/header_logo"
        app:viewpager_pagerTitleStrip="@layout/sliding_strip"
        app:viewpager_logoMarginTop="100dp"
        app:viewpager_color="@color/colorPrimary"
        app:viewpager_headerHeight="200dp"
        app:viewpager_headerAlpha="1.0"
        app:viewpager_imageHeaderDarkLayerAlpha="0.2"
        app:viewpager_enableToolbarElevation="true"
        app:viewpager_parallaxHeaderFactor="1.5"
        app:viewpager_headerAdditionalHeight="3.5dp"
        app:viewpager_displayToolbarWhenSwipe="false"
        app:viewpager_transparentToolbar="false" 
        app:viewpager_animatedHeaderImage="true"

        />
`
When scrolling the viewpager still thinks it has a toolbar and hence still leaves padding for the toolbar.

**Comment by ahujakaran24** [comment]
I am facing same issue, @osiloke how did you fix this?

**Comment by osiloke** [comment]
Uhm, look at my new xml declaration

<com.github.florent37.materialviewpager.MaterialViewPager
        app:viewpager_disableToolbar="true"
        android:id="@+id/materialViewPager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:viewpager_logo="@layout/header_logo"
        app:viewpager_pagerTitleStrip="@layout/sliding_strip"
        app:viewpager_logoMarginTop="100dp"
        app:viewpager_color="@color/primary"
        app:viewpager_headerHeight="200dp"
        app:viewpager_headerAlpha="1.0"
        app:viewpager_imageHeaderDarkLayerAlpha="0.2"
        app:viewpager_hideLogoWithFade="true"
        app:viewpager_hideToolbarAndTitle="true"
        app:viewpager_enableToolbarElevation="true"
        app:viewpager_parallaxHeaderFactor="1.5"
        app:viewpager_headerAdditionalHeight="20dp"
        app:viewpager_displayToolbarWhenSwipe="true"
        app:viewpager_transparentToolbar="false"
        app:viewpager_animatedHeaderImage="true"

        />
