### ISSUE TITLE
Error/bug

### ISSUE THREAD

**Issue by MatteCarra** [florent37/MaterialViewPager#190]
Where is the bug?
![device-2015-12-06-154830](https://cloud.githubusercontent.com/assets/11074527/11613877/eefd152c-9c30-11e5-99d3-6623f93f7c0c.png)

**Comment by vitorprado** [comment]
Same problem here. +1

**Comment by vitorprado** [comment]
I found the solution reading another issue.
You're using the wrong adapter in your recyclerView.. you need to change to this:

```java
yourViewPager.setAdapter(new RecyclerViewMaterialAdapter(new YourAdapter(context)));
```

instead of using `YourAdapter` directly.


@florent37 I think this explanation about the adapter should be in documentation or inside the READ_ME file.

**Comment by MatteCarra** [comment]
Yes
