### ISSUE TITLE
Can't open with android studio.

### ISSUE THREAD

**Issue by EgyptianM** [florent37/MaterialViewPager#191]
I have this error when trying to open the project in android studio
Error:(3, 0) Cause: org/gradle/api/publication/maven/internal/DefaultMavenFactory

**Comment by elkyzmich** [comment]
I have some problem. Hope, somebody help us.

**Comment by vitorprado** [comment]
This can be a problem with your gradle version, sometimes you have an installation of gradle in your machine and the project try to use another.. Try change your settings inside IDE preferences in: `Build, Execution, Deployment > Build Tools > Gradle > Project-level settings` to `Use default gradle wrapper`

**Comment by EgyptianM** [comment]
@vitorprado Thanks I'll try it.

**Comment by vitorprado** [comment]
@EgyptianM @elkyzmich problem solved?

**Comment by elkyzmich** [comment]
@vitorprado Yes, thanks a lot

**Comment by vitorprado** [comment]
@EgyptianM @florent37 can you close the issue? thanks.

**Comment by EgyptianM** [comment]
Hello @vitorprado 
I did what you said but unfortunately I have this error now

Error:(14, 0) Plugin with id 'io.fabric' not found.

Thank you for your efforts

**Comment by elkyzmich** [comment]
@EgyptianM add to gradle
dependencies {
    classpath 'io.fabric.tools:gradle:1.+'
}

**Comment by EgyptianM** [comment]
@elkyzmich I added but this is what I got

`Error:Could not find any version that matches io.fabric.tools:gradle:1.+.`

**Comment by vitorprado** [comment]
@EgyptianM follow this: https://docs.fabric.io/android/fabric/integration.html

it's not a problem related to the lib.. it's another gradle problem.
I think you should close the issue.

**Comment by EgyptianM** [comment]
OK thank you very much.
