### ISSUE TITLE
The last tab item string not shown completely

### ISSUE THREAD

**Issue by jinxk** [florent37/MaterialViewPager#20]
I am using most of the code from the sample except for my own tabs -
This is how it's shown
![screenshot_2015-05-11-13-34-45 1](https://cloud.githubusercontent.com/assets/11273537/7560648/c4a4ebb2-f7e2-11e4-8c7a-8042bb1c5763.png)

The tab should show the complete tab name "Borrowed"
I also tried -
```
mViewPager.getPagerTitleStrip().setShouldExpand(true);
```
didn't work.

**Comment by florent37** [comment]
You have to include you own tab layout,
look at the PagerTitleStrip Readme
https://github.com/jpardogo/PagerSlidingTabStrip

**Comment by jinxk** [comment]
Thanks! I set up a custom tab and had to change the padding (from your given example) to 16dp to get it to work.
