### ISSUE TITLE
Why view pager display in black color 

### ISSUE THREAD

**Issue by MBehtemam** [florent37/MaterialViewPager#202]
i try to use MaterialViewPager and everything work ok except the color : 
![2015-12-26_18-47-15](https://cloud.githubusercontent.com/assets/1811124/12006926/47e96e08-ac01-11e5-989e-57ac6f04bb74.jpg)

and this is my style.xml file : 

<resources xmlns:tools="http://schemas.android.com/tools">

    
    
        
        
        
        
    

    
    

    <style name="AppBaseTheme" parent="@style/Theme.AppCompat.Light">
    </style>

    
    <style name="AppTheme" parent="AppBaseTheme">

        <item name="android:textColorPrimary">@android:color/white</item>
        <item name="drawerArrowStyle">@style/DrawerArrowStyle</item>
        <item name="android:windowTranslucentStatus" tools:targetApi="19">true</item>

        <item name="android:windowContentOverlay">@null</item>
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>

        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/accent_color</item>

        <item name="android:statusBarColor" tools:targetApi="21">@color/statusBarColor</item>
        <item name="android:navigationBarColor" tools:targetApi="21">@color/navigationBarColor</item>
        <item name="android:windowDrawsSystemBarBackgrounds" tools:targetApi="21">true</item>

    </style>

    <style name="DrawerArrowStyle" parent="Widget.AppCompat.DrawerArrowToggle">
        <item name="spinBars">true</item>
        <item name="color">@color/drawerArrowColor</item>
    </style>

</resources>

**Comment by bloder** [comment]
The default header's color is black, this style just make design shows in your main view's preview, but its easy to do what you want, you just need to set an image and a color in header.

**Comment by bloder** [comment]
try this:

mViewPager.setMaterialViewPagerListener(new MaterialViewPager.Listener() {
            @Override
            public HeaderDesign getHeaderDesign(int page) {
                switch (page) {
                    case 0:
                        return HeaderDesign.fromColorResAndUrl(
                                R.color.blue,
                                "http://cdn1.tnwcdn.com/wp-content/blogs.dir/1/files/2014/06/wallpaper_51.jpg");
                    case 1:
                        return HeaderDesign.fromColorResAndUrl(
                                R.color.green,
                                "https://fs01.androidpit.info/a/63/0e/android-l-wallpapers-630ea6-h900.jpg");
                    case 2:
                        return HeaderDesign.fromColorResAndUrl(
                                R.color.cyan,
                                "http://www.droid-life.com/wp-content/uploads/2014/10/lollipop-wallpapers10.jpg");
                    case 3:
                        return HeaderDesign.fromColorResAndUrl(
                                R.color.red,
                                "http://www.tothemobile.com/wp-content/uploads/2014/07/original.jpg");
                }

                //execute others actions if needed (ex : modify your header logo)

                return null;
            }
        });

**Comment by bloder** [comment]
try this following code:


    mViewPager.setMaterialViewPagerListener(new MaterialViewPager.Listener() {
            @Override
            public HeaderDesign getHeaderDesign(int page) {
                switch (page) {
                    case 0:
                        return HeaderDesign.fromColorResAndUrl(
                                R.color.blue,
                                "http://cdn1.tnwcdn.com/wp-content/blogs.dir/1/files/2014/06/wallpaper_51.jpg");
                    case 1:
                        return HeaderDesign.fromColorResAndUrl(
                                R.color.green,
                                "https://fs01.androidpit.info/a/63/0e/android-l-wallpapers-630ea6-h900.jpg");
                    case 2:
                        return HeaderDesign.fromColorResAndUrl(
                                R.color.cyan,
                                "http://www.droid-life.com/wp-content/uploads/2014/10/lollipop-wallpapers10.jpg");
                    case 3:
                        return HeaderDesign.fromColorResAndUrl(
                                R.color.red,
                                "http://www.tothemobile.com/wp-content/uploads/2014/07/original.jpg");
                }

                //execute others actions if needed (ex : modify your header logo)

                return null;
            }
        });

**Comment by MBehtemam** [comment]
@bloder thanks for your answering. if image for header is placed in asset folder or in sd card and not drawable or in internet url how can use this image.

**Comment by bloder** [comment]
you need to put this image in drawable folder to use it, it`s very simple to do it just copy and paste in drawable folder

**Comment by bloder** [comment]
or you can try use it with Picasso lib i dont know if it work

**Comment by MBehtemam** [comment]
yes i use Picasso in my project, but do you know how to use Picasso with MaterialViewPager

**Comment by bloder** [comment]
Copy and paste your images in a drawable folder, and next you just need to use Picasso getting your image in that drawable folder like this example:

Picasso.with(context).load(R.drawable.drawableName).into(imageView);

**Comment by MBehtemam** [comment]
@bloder  thanks
