### ISSUE TITLE
How to change the menu background color？

### ISSUE THREAD

**Issue by WaylanPunch** [florent37/MaterialViewPager#204]
In the styles.xml file, the **textColorPrimary** is white and the theme is **Theme.AppCompat.Light.NoActionBar**.

Here is the problem, I want keep the light theme and the white textcolor but I need menu item text color to be another color, how can I achieve that?

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.main, menu);
        return true;
    }

By the way, setting style like below won't work.

	<item name="android:actionMenuTextAppearance">@style/MenuTextStyle</item>

	<style name="MenuTextStyle">
        <item name="android:textColor">@android:color/black</item>
        <item name="android:textSize">18sp</item>
    </style>

![menu](http://i4.tietuku.com/abf4fe5aea3ba838.png)

**Comment by WaylanPunch** [comment]
And there is any trigger to make the logo.png disappear when scroll up the fragment?

**Comment by bloder** [comment]
try this action bar generator - http://jgilfelt.github.io/android-actionbarstylegenerator/#name=example&compat=holo&theme=light&actionbarstyle=solid&texture=0&hairline=0&neutralPressed=1&backColor=E4E4E4%2C100&secondaryColor=D6D6D6%2C100&tabColor=33B5E5%2C100&tertiaryColor=F2F2F2%2C100&accentColor=33B5E5%2C100&cabBackColor=FFFFFF%2C100&cabHighlightColor=33B5E5%2C100

**Comment by bloder** [comment]
just copy the code and paste in your project

**Comment by ChristopheVersieux** [comment]
Bloating the app with all the drawables doesn't looks like a good idea when a theme would be enough ;-)
