### ISSUE TITLE
Can't load a picture. Something wrong in URL?

### ISSUE THREAD

**Issue by MarKco** [florent37/MaterialViewPager#21]
Hello,
I'm implementing MaterialViewPager and I'd like to have this picture as header background: https://photo1.hotelsclick.com/venice/21186/grandi/best-western-albergo-san-marco-facciata.73.jpg

I noticed it doesn't work, the picture can't be loaded. But I don't get any error in the logs and I don't know what's wrong with it. I'm pretty sure the issue is in the URL or in the way the picture gets loaded, because if I download the picture and load it into another server on another url (say http://www.marcozanetti.it/blog/wp-content/uploads/2015/05/best-western-albergo-san-marco-facciata.73.jpg) it works perfectly.

Do you happen to know what could be this due to? Is this maybe a Picasso issue? I tried to clone MaterialViewPager library in order to add it as library source project and debug picture loading but couldn't make it to add the library to the project :-/

Please let me know if I can provide further data in order to find a proper solution, for me and for others who could be experiencing the same issue.

**Comment by omidheshmatinia** [comment]
i guess its because of dash "-"  in the image url !
i had the same problem once in which the image loading library didn't work with NON ENGLISH images names and images with "-" in the url

**Comment by MarKco** [comment]
Hello,
I solved the issue myself, it was (oddly enough) due to a server mistake in https handling :-/

Sorry for bothering
