### ISSUE TITLE
Save HeaderImage in local storage, please help

### ISSUE THREAD

**Issue by Murgio** [florent37/MaterialViewPager#214]
Hey, 
I've been trying now for a couple of hours to save the HeaderImage which I am setting with HeaderDesign.fromColorAndUrl into the local storage. So my idea is, if the user has no internet connection that the user has still an image in the Header wich is stored in the local storage. But I am not able to do it. So if anyone has an idea how this can be accomplished I would be really grateful.

**Comment by bloder** [comment]
Try to put that image in your drawable folder and change your Header Design Color and Url function to HeaderDesign.fromColorResAndDrawable. Hope it helps you!

**Comment by Murgio** [comment]
Thank you for your answer. But I have to be able to get images from the internet. So if you got an another answer I would be really grateful.

**Comment by bloder** [comment]
Ok, how many images do you pretend save in storage? Just headers images?

**Comment by Murgio** [comment]
Yes, there is a total of 4 tabs so that equals 4 different images.

**Comment by Murgio** [comment]
So here is my current state. I changed the MaterialViewPagerImageHelper script that "setImageURL" looks like this: 
![screenshot_1](https://cloud.githubusercontent.com/assets/17013257/12749731/d866d6ae-c9b2-11e5-8350-df945e4b592b.png)

Then in my MainActivity.java I set the image like this:
![screenshot_2](https://cloud.githubusercontent.com/assets/17013257/12749758/fa7dfc22-c9b2-11e5-863f-258d6855bc37.png)

But it isn't working.

**Comment by bloder** [comment]
Ok you can try this solution (I never tested it before) : 

1 - Put all header images in the drawable folder.

2 - Write a boolean function that verify the internet connection. ---(http://stackoverflow.com/questions/4238921/detect-whether-there-is-an-internet-connection-available-on-android)

3 - Write two functions returning HeaderDesign, one function you will pass that internet link when you return the image and other function you will return your drawable resource link like this - 

FIRST FUNCTION -

                   public HeaderDesign getHeaderDesignOnline(int page) {
                switch (page) {
                    case 0:
                        return HeaderDesign.fromColorResAndUrl(
                                R.color.blue,
                                "http://cdn1.tnwcdn.com/wp-content/blogs.dir/1/files/2014/06/wallpaper_51.jpg");
                    case 1:
                        return HeaderDesign.fromColorResAndUrl(
                                R.color.green,
                                "https://fs01.androidpit.info/a/63/0e/android-l-wallpapers-630ea6-h900.jpg");
                      }

SECOND FUNCTION -

                    public HeaderDesign getHeaderDesignOffline(int page) {
                switch (page) {
                    case 0:
                        return HeaderDesign.fromColorResAndUrl(
                                R.color.blue,
                                "android.resource://your_package_name/drawable/your_image_name");
                    case 1:
                        return HeaderDesign.fromColorResAndUrl(
                                R.color.green,
                                "android.resource://your_package_name/drawable/your_image_name");
                      }

4 - Verify if app has connection, if it has, you call the first function else you call the second like this -

                   ...
                   hasInternet() ? getHeaderDesignOnline(page) : getHeaderDesignOffline(page);
                   ...

I dont know if it will work, I hope it helps you!

**Comment by Murgio** [comment]
Thank you very much @bloder 
I managed to do it in a different way but thank you for your answers!
