### ISSUE TITLE
Do arrayLists work with Material View Pager RecyclerView Fragments?

### ISSUE THREAD

**Issue by karanschhabra** [florent37/MaterialViewPager#216]
i am a newbie and would kindly like to know if arrayLists work with Material View Pager RecyclerView Fragments

**Comment by bloder** [comment]
Yes it works, you just need to create a fragment adapter and pass the object array there. I don't have an example using objects array but maybe this fragment adapter example helps you! 

https://github.com/bloder/megan-fox-layout/blob/master/app/src/main/java/br/com/bloder/layouttest/ChannelsFragmentAdapter.java

**Comment by karanschhabra** [comment]
thannks a lot
