### ISSUE TITLE
Can't change Tabs Title Color in xml or Java Object

### ISSUE THREAD

**Issue by Michazzz** [florent37/MaterialViewPager#22]
Hi! 
I need to change tabs titles color from ViewPager xml file or Java object without change color in styles.
How i can do this?

**Comment by MarKco** [comment]
I managed to do so by implementing my my_tabs.xml and then setting in it android:textColor="@android:color/whatever" and app:pstsTextColorSelected="@color/whichever"
It seems to work, even though it'd be better to be able to change those colors without implementing a custom tab bar.

**Comment by Michazzz** [comment]
Ok, thanks for quickly response!

**Comment by MarKco** [comment]
Also, if you want to change tabs background, you should do this: app:pstsTabBackground="@color/transparent_background_for_textviews"

**Comment by Michazzz** [comment]
Is possible to change TabBackground color via mViewPager.getPagerTitleStrip().setTabBackground(color) ?

**Comment by MarKco** [comment]
Yes, you can! :-)

**Comment by Michazzz** [comment]
So I'm doing womething wrong i think because I'm trying to use that method on FragmentStatePagerAdapter inside method setPrimaryItem. In sample you set there a color of image background

**Comment by MarKco** [comment]
That's where I tried it, and it worked. Did you also put a tabBackgrouns in XML? Could there be a clash of definitions here between XML and java code?
