### ISSUE TITLE
How to add a "Pull to Refresh"

### ISSUE THREAD

**Issue by LeeXiaofan** [florent37/MaterialViewPager#225]
I use the "Phoenix Pull-to-Refresh",but it appears on the top of the "Material ViewPager".how can i solve it.

**Comment by willu2** [comment]
You have to add Pull-to-Refresh widget in main xml. Like this:

`<android.support.v4.widget.SwipeRefreshLayout
        android:id="@+id/swipe
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:paddingLeft="@dimen/activity_horizontal_margin"
        android:paddingRight="@dimen/activity_horizontal_margin"
        android:paddingTop="@dimen/activity_vertical_margin"
        android:paddingBottom="@dimen/activity_vertical_margin"
        ">
    <com.github.florent37.materialviewpager.MaterialViewPager
        android:id="@+id/materialViewPager"
               ........
        />
    </android.support.v4.widget.SwipeRefreshLayout>`

**Comment by willu2** [comment]
You can add Pull-to-Refresh widget in fragment_recyclerview xml. Like this (it's will be better):
 <android.support.v4.widget.SwipeRefreshLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:paddingLeft="@dimen/activity_horizontal_margin"
        android:paddingRight="@dimen/activity_horizontal_margin"
        android:paddingTop="@dimen/activity_vertical_margin"
        android:paddingBottom="@dimen/activity_vertical_margin"
        android:id="@+id/swipe">
    <android.support.v7.widget.RecyclerView
        android:id="@+id/recycler_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"

    />
</android.support.v4.widget.SwipeRefreshLayout>

**Comment by LeeXiaofan** [comment]
I will have a try,thanks! :)
