### ISSUE TITLE
items overlaps header and tabs on orientation change 

### ISSUE THREAD

**Issue by aftabsikander** [florent37/MaterialViewPager#23]
I am using the latest code still this issues is being faced by me. When I rotate the device after scrolling few list items if I now rotate the device the issue happens see the image for more details
![screenshot_2015-05-13-16-39-36](https://cloud.githubusercontent.com/assets/4800511/7609860/5c5eb682-f92c-11e4-9b32-fb725f72ee24.png)

The above screenshot is taken after I rotate the device from landscape to portrait mode.

Any fix for this issue

**Comment by florent37** [comment]
I saw this, don't know hot to fix for now.

Maybe with saveinstancestate.

You can avoir this with locking into portrait for now, not a solution but I don't have another solution...

**Comment by mostafazakaria** [comment]
The same Issue happened with me.I am trying to load data from network request in background then fill RecyclerView Adapter with the retrieved data then the issue happens , and that means I should fill adapter in OnViewCreated and that is not doable in my case. 

Any Solutions ??

**Comment by florent37** [comment]
fixed on 1.0.4
