### ISSUE TITLE
[question] Using Glide to load images into headers instead of Picasso

### ISSUE THREAD

**Issue by BrandonSlaght** [florent37/MaterialViewPager#232]
Is there a way to do this?  I ask because I have been running into some memory issues with my app, as I load headers from dynamic network sources and the images have unbounded resolution.  Picasso I know does not resize images to fit in `ImageViews` whereas Glide does, making it a lot more efficient.

**Comment by willu2** [comment]
Picasso.with(this)
    .load("http://nuuneoi.com/uploads/source/playstore/cover.jpg")
    .resize(250, 120)  <<<<<<<<<<<<<<<
    .into(ivImgPicasso);

**Comment by BrandonSlaght** [comment]
Turns out this is pointless anyways because the Picasso call uses .resize(), so it uses the same amount of memory as Glide.
