### ISSUE TITLE
New 'com.android.support:appcompat-v7:23.2.1' makes the app crash

### ISSUE THREAD

**Issue by PedroBarbosaPT** [florent37/MaterialViewPager#236]
Hi.
I tried to update the appcompact and it makes the app crashes with the error:

> This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.

What should i do?

**Comment by vitorprado** [comment]
Use the '.NoActionBar' theme in your activity.
