### ISSUE TITLE
Change text in tab title dynamically?

### ISSUE THREAD

**Issue by willu2** [florent37/MaterialViewPager#244]
How i can change text in tab title dynamically?
If i need restart FragmentStatePagerAdapter (getPageTitle(int position)) every time?

**Comment by bloder** [comment]
Did you already try this?

    Tab tab = super.getSupportActionBar().getTabAt(yourTabPosition); 
    tab.setText("new Title");

**Comment by pcodemang** [comment]
> Did you already try this?

Is there anyway to move the title to where the custom logo (Material Is Good) would be?

**Comment by florent37** [comment]
please look at https://github.com/jpardogo/PagerSlidingTabStrip
