### ISSUE TITLE
Save/Restore recycler view scroll position in fragment

### ISSUE THREAD

**Issue by Khang-NT** [florent37/MaterialViewPager#245]
I want to save recycler view scroll position to restore it whenever user rotate the screen. How can I do that? I have tried to restore scroll position by :
`MaterialViewPagerHelper.registerRecyclerView(getActivity(), mRecyclerView, null);`
`...`
`((LinearLayoutManager) layoutManager).scrollToPosition(savedPosition);`
And result like that:
![Image of Yaktocat](http://i.imgur.com/Slv7NDU.png)

Recycler view scrolled up but MaterialViewPager not update, toolbar layout still transparent.

**Comment by bloder** [comment]
I think this is the same bug that issue https://github.com/florent37/MaterialViewPager/issues/237

Could you show me how you're setting material adapter? If you couldn't I did a example using this lib
maybe helps you with this bug... https://github.com/bloder/megan-fox-layout
