### ISSUE TITLE
How to use server data in MaterialViewPager

### ISSUE THREAD

**Issue by PeterPhyo** [florent37/MaterialViewPager#249]
mViewPager.getViewPager().setAdapter(new FragmentStatePagerAdapter(getSupportFragmentManager()) {

String[] categories = new String[]{"Foods", "Fashion", "Electronic", "Material"}; //   static, want to change data from server. 

            @Override
            public Fragment getItem(int position) {
                switch (position % 4) {
                    //case 0:
                    //    return RecyclerViewFragment.newInstance();
                    //case 1:
                    //    return RecyclerViewFragment.newInstance();
                    //case 2:
                    //    return WebViewFragment.newInstance();
                    default:
                        return RecyclerViewFragment.newInstance();
                }
            }

            @Override
            public int getCount() {
                return categoryName.size();
            }

            @Override
            public CharSequence getPageTitle(int position) {
                return categoryName.get(position);
            }
        });

------

        NetworkEngine.getInstance().getFoodCategory(new Callback<ArrayList<FoodCategory>>() {
            @Override
            public void success(ArrayList<FoodCategory> foodCategories, Response response) {
                
            }

            @Override
            public void failure(RetrofitError error) {

            }
        });

**Comment by florent37** [comment]
http://tutos-android-france.com/retrofit-webservices-rest/
