### ISSUE TITLE
Flickering of fragments when using ObservableScrollView or ObservableListView

### ISSUE THREAD

**Issue by jaredrummler** [florent37/MaterialViewPager#25]
This is an issue in [Android-ObservableScrollView](https://github.com/ksoichiro/Android-ObservableScrollView). See: https://github.com/ksoichiro/Android-ObservableScrollView/issues/117

To fix it you could add the following code in registerScrollView and registerListView in MaterialViewPagerAnimator.

```java
public void registerScrollView(final ObservableScrollView scrollView,
        final ObservableScrollViewCallbacks observableScrollViewCallbacks) {
    if (scrollView != null) {
        scrollViewList.add(scrollView); // add to the scrollable list
        // fix flickering
        scrollView.setTouchInterceptionViewGroup((ViewGroup) scrollView.getParent().getParent());
        ...
```

```java
public void registerListView(final ObservableListView listView,
        final ObservableScrollViewCallbacks observableScrollViewCallbacks) {
    if (listView != null) {
        scrollViewList.add(listView); // add to the scrollable list
        listView.setTouchInterceptionViewGroup((ViewGroup) listView.getParent().getParent());
        ...
```

This will use the `RelativeLayout` in `material_view_pager_layout.xml` as the `ViewGroup`. Inspired by this workaround: https://github.com/ksoichiro/Android-ObservableScrollView/commit/f17e3ce67686fc47cff664a199c96f821affdea8

**Comment by florent37** [comment]
can you do create a pull request with this code please ?

**Comment by NogerbekNurzhan** [comment]
@florent37 Check this. Its the same as here [Click here](https://github.com/ksoichiro/Android-ObservableScrollView/commit/f17e3ce67686fc47cff664a199c96f821affdea8)

**Comment by florent37** [comment]
thanks for your help :+1: I really appreciate it :smile: 
I sent it to the 1.0.3.3

**Comment by Anearion** [comment]
Is this fixed somehow ? I'm experiencing this right now. My third tab is an observableScrollView and if I touch the content this fragment flick to my second tab tab, which is a recyclerview.

**Comment by egor-n** [comment]
For anyone still encountering this issue, your `registerScrollView` should happen after the view has been attached to the window.

There is a [condition](https://github.com/florent37/MaterialViewPager/blob/85a124898b76127af2b9a7d2cb993a1011fde15e/materialviewpager/src/main/java/com/github/florent37/materialviewpager/MaterialViewPagerAnimator.java#L384) for the `ScrollView`'s parent to be not null, which can be false in `onCreateView`, for example.

**Comment by youtoou2** [comment]
@Anearion thanks to @egor-n , just register your scrollview after onStart() to make sure the view is attached. I'm having the same issue and registering it in onCreateView() , finally it is working fine.
