### ISSUE TITLE
Default Value Change Please(Log)

### ISSUE THREAD

**Issue by jypDev** [florent37/MaterialViewPager#269]
public class MaterialViewPagerAnimator { 

public static Boolean ENABLE_LOG = true;    <---- false

...

I don't want to add the line.

**Comment by jintoga** [comment]
if you want to turn off Log then use this: 
MaterialViewPagerAnimator.ENABLE_LOG = false;

**Comment by jypDev** [comment]
I want to say that it should be changed from the default setting.
