### ISSUE TITLE
MaterialViewPager Background color

### ISSUE THREAD

**Issue by kaaantunaa** [florent37/MaterialViewPager#27]
Hi,

First of all thanks for making this library. :) 

I got a problem after you updated to 1.0.3.3 version setColor doesn't work properly anymore.

_pager.setColor(Color.parseColor(_model.color), 0);

I think the problem is related with MaterialViewPagerAnimator.java 

Could you please check it ?

**Comment by florent37** [comment]
I just checked and it works
