### ISSUE TITLE
Strange bahaviour with RecyclerView

### ISSUE THREAD

**Issue by MarKco** [florent37/MaterialViewPager#28]
Hello everybody,
I'm implementing MaterialViewPager with several fragments. One of them is a simple RecyclerView. This is my fragment XML

    <?xml version="1.0" encoding="utf-8"?>
    <com.github.ksoichiro.android.observablescrollview.ObservableScrollView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/scrollView"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <include layout="@layout/material_view_pager_placeholder" />

        <android.support.v7.widget.RecyclerView
            android:id="@+id/details_list"
            android:layout_width="match_parent"
            android:layout_height="300dp">

        </android.support.v7.widget.RecyclerView>

    </LinearLayout>
    </com.github.ksoichiro.android.observablescrollview.ObservableScrollView>

and this is my main activity xml:

    <com.github.florent37.materialviewpager.MaterialViewPager
    android:id="@+id/materialViewPager"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:viewpager_pagerTitleStrip="@layout/my_tabs"
    app:viewpager_logoMarginTop="100dp"
    app:viewpager_headerHeight="200dp"
    app:viewpager_headerAlpha="1"
    app:viewpager_color="@color/hc_blu_toolbar"
    app:viewpager_hideLogoWithFade="true"
    app:viewpager_hideToolbarAndTitle="false"
    android:textColor="@android:color/white"
    app:viewpager_enableToolbarElevation="true"
    app:viewpager_parallaxHeaderFactor="1.5"
    app:viewpager_headerAdditionalHeight="0dp"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto" />

Now, what happens is that while custom layouts (for other fragments) without listViews or recyclerVires get loaded smoothly, with header picture and all, this RecyclerView of mine behaves strangely: it seems like there's a huge padding above the recyclerView itself and a smaller one above it. Also, picture is not loaded in the header.

This is a sort of screencast I made in order to let you know what I'm talking about.

![screencast_viewpager](https://cloud.githubusercontent.com/assets/1422362/7702735/ae484462-fe32-11e4-9e46-06e1149bc1f9.gif)

I think all is fine in my code, of course. Recyclerview's content are the ones I expect and everything works, except for this bad, bad behaviour when scrolling and the too-large-top-and-bottom-paddings.

I have no clue about how to get out of this. Do you have any idea?

Thank you

**Comment by MarKco** [comment]
As you can see, on another layout (of the same viewPager) everything works smoothly.

Layout:

<?xml version="1.0" encoding="utf-8"?>
<com.github.ksoichiro.android.observablescrollview.ObservableScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/scrollView"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <include layout="@layout/material_view_pager_placeholder" />

        <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            android:visibility="gone">

            <RelativeLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="top|right"
                android:layout_marginRight="10dp">

                <RatingBar
                    android:id="@+id/hotel_stars"
                    style="@style/Widget.AppCompat.RatingBar"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:clickable="false"
                    android:focusable="false"
                    android:isIndicator="true"
                    android:numStars="5"
                    android:rating="0"
                    android:stepSize="0.1" />

            </RelativeLayout>

        </FrameLayout>

        <TextView
            android:id="@+id/hotel_name"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:autoText="true"
            android:textAlignment="gravity"
            android:paddingTop="10dp"
            android:paddingBottom="5dp"
            style="@style/hotelNameForDetails" />

        <Button
            android:layout_marginTop="20dp"
            android:id="@+id/book_now"
            style="@style/Button.wide"
            android:minHeight="55dp"/>

        <TextView
            android:id="@+id/hotel_address"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:paddingLeft="@dimen/details_padding_left"
            android:paddingRight="@dimen/details_padding_left"
            android:paddingTop="15dp"
            android:paddingBottom="10dp"
            android:textSize="@dimen/details_text_size" />

        <TextView
            android:id="@+id/hotel_details_description"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            style="@style/hotelDescriptionForDetails"/>

    </LinearLayout>
</com.github.ksoichiro.android.observablescrollview.ObservableScrollView>

Result:

![output_wyhpbr](https://cloud.githubusercontent.com/assets/1422362/7703397/fb1811e6-fe37-11e4-9528-0a274900a42b.gif)

**Comment by florent37** [comment]
Please do not use ScrollView & RecyclerView, choose only One :smile:

**Comment by MarKco** [comment]
Thank you Florent,
I tried and it almost works.
Just of couple of questions:

1- It almost works, but doesn't really work. I get the right animation in the ViewPager but the margin above the list is still huge and the list does not scroll completely until the ViewPager entries. You can see what I mean in the picture below.
(Also the header pictures loads every now and then, but I think this is due to another bug still open so I don't see it much as a issue right now.)

![output_mi88o3](https://cloud.githubusercontent.com/assets/1422362/7707276/4ed23af2-fe4f-11e4-9924-2444f9d455d7.gif)

2- Replacing the ScrollView with the RecyclerView is ok for this purpose, since I don't need to have anything above my RecyclerView. But what if I need to have a vertical Linear Layout with a TextView and, below that, a list of items? I don't want the list of items to be scrollable, I just want it to overflow the screen just like the text in the screenshot above. Once the user scrolls, the whole list should scroll up together with the Textview above and behave just like the screenshot above (but better).

Thank you

**Comment by MarKco** [comment]
Ok,
I tried with the ListView.

This is the layout:

    <?xml version="1.0" encoding="utf-8"?>
    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <include layout="@layout/material_view_pager_placeholder" />

    <TextView
        style="@style/grey_header_textview"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="20dp"
        android:text="@string/requested_rooms" />

    <TextView
        android:id="@+id/search_type"
        style="@style/white_blue_text_textview"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

    <TextView
        style="@style/grey_header_textview"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

    <com.towers.hotelsclick.utils.TariffsListView
        android:id="@+id/tariffs_list"
        android:layout_width="match_parent"
        android:layout_height="300dp">

    </com.towers.hotelsclick.utils.TariffsListView>

    </LinearLayout>

And this is what happens:

![output_nxyjhz](https://cloud.githubusercontent.com/assets/1422362/7713054/73c6886a-fe75-11e4-8468-9b3a470a9251.gif)

:-/ Do you have any suggestion for me or is this something I can't achieve with MaterialViewPager? (I hope not, it took me a certain effort to come to this point :-) )

Thank you

**Comment by florent37** [comment]
Please do not use ListView & ScrollView at the same time, please choose...
And do not use ListView, use RecyclerView

Just use your TariffsListView and fill it with your content.
In your case the listview is below your material_view_pager_placeholder so il only get 1/2 of screen help...

<com.towers.hotelsclick.utils.TariffsListView
    android:id="@+id/tariffs_list"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

</com.towers.hotelsclick.utils.TariffsListView>

**Comment by MarKco** [comment]
Florent,
I don't want to be offensive, but your reply was not so helpful. I had already removed the ScrollView, as you can see by the example I provided. The only ScrollView I had now was in the layout without ListView or RecyclerView, which worked (and had always been).

Anyway your reply was somehow useful because it got me the idea to remove the material_view_pager_placeholder, which apparently is not needed when using just a ListView or RecyclerView. Finally I made it by removing such layout and setting the height of the RecyclerView to match_parent.

Thus, I didn't know how to have a layout above my ListView, since apparently I can only choose between "any layout, without lists" or "just list". I got what I wanted by using a composite RecyclerView with a header and a list of regular items. Maybe one of these days I'll be posting a small tutorial about it, since I guess many others will face this issue after me.

Regards

**Comment by championswimmer** [comment]
You have forgotten to document that the adapter of the recyclerview must be `new RecyclerViewMaterialAdapter`

**Comment by masiha68** [comment]
sorry .. i have same issue
how i can fix it ...
when recyclerView scrolling same item get hidden
