### ISSUE TITLE
Solved the scrolling issue. Have a look at it. (not issue, an advice)

### ISSUE THREAD

**Issue by nuhkoca** [florent37/MaterialViewPager#283]
I was facing that problem till 2 days ago. Hovewer I solved that problem adding layout_behavior:appbar_scrolling_view_behavior to my SwipeRefreshLayout or RecyclerView. It works perfectly on me.

> Here is an example code block.

```
<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.SwipeRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/swipe_news"
    android:layout_height="wrap_content"
    android:layout_width="match_parent"
    app:layout_behavior="@string/appbar_scrolling_view_behavior">

<android.support.v7.widget.RecyclerView
    android:id="@+id/recyclerView"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />

</android.support.v4.widget.SwipeRefreshLayout>
```

**Comment by dearvinitsr** [comment]
I believe , This is the for issue having multiple fragment and scrolling on one influence the other and leave a gap on top?

Strangely it has solved my issue. @nuhkoca

**Comment by nuhkoca** [comment]
@dearvinitsr yes :)

**Comment by hmathur127** [comment]
appbar scrolling view behaviour not working for me.
also below code is not working..
MaterialViewPagerHelper.getAnimatorContext(context).onMaterialScrolled(null,0)

please help

**Comment by shahimclt** [comment]
is `MaterialViewPagerHelper.getAnimatorContext(context).onMaterialScrolled(null,0)` still available? I am not able to call that method.

**Comment by vaxi87** [comment]
You can use reflection to invoke that method.

`val animator = MaterialViewPagerHelper.getAnimator(context)
  val method = animator.javaClass.getDeclaredMethod("onMaterialScrolled", Any::class.java, Float::class.javaPrimitiveType)
  method.isAccessible = true
  method.invoke(animator, null, 0)
    `

**Comment by chnouman** [comment]
@nuhkoca  dear i'm still having problem but problem occur some time some time it works totally fine. please can you help me.
