### ISSUE TITLE
Gradle unable to resolve dependency for Materialviewpager library

### ISSUE THREAD

**Issue by eatyoveshtables** [florent37/MaterialViewPager#29]
I've been unable to compile Materialviewpager as a gradle dependency. I've included it exactly as specified in the documentation. I've been able to compile other third-party libraries via gradle with no problem. Please see the screenshot of the exact error below.  Thanks for your help!
``
dependencies {
    compile ('com.github.florent37:materialviewpager:1.0.3.3@aar'){
        transitive = true
    }
}
``

![screen shot 2015-05-19 at 3 44 30 pm](https://cloud.githubusercontent.com/assets/6718711/7712222/00839848-fe3e-11e4-9ca8-1cf9050f6850.png)

**Comment by florent37** [comment]
I tried it in a new empty project
`compile ('com.github.florent37:materialviewpager:1.0.3.3@aar'){ transitive = true }`

and it works,
can you send me your full build.gradle please ?

**Comment by eatyoveshtables** [comment]
Okay - here's a gist for the full file: https://gist.github.com/eatyoveshtables/caa2b8defb4da8a3eff6

**Comment by DevendraSingh91** [comment]
same here. @florent37  did you solve your issue @eatyoveshtables ?

**Comment by florent37** [comment]
can you try with 1.0.4 ?

@DevendraSingh91 can you make a pull request with this please ?

**Comment by DevendraSingh91** [comment]
that was done @florent37  Thanks.

**Comment by eatyoveshtables** [comment]
Hi sorry, what was the conclusion here @florent37? I just tried with version 1.0.4 and I'm getting the same error. The minSdkVersion of my project is 10 and that seems to work fine when compiling Materialviewpager as a separate library.
