### ISSUE TITLE
Header with RESTful

### ISSUE THREAD

**Issue by nuhkoca** [florent37/MaterialViewPager#295]
Hi All,

I have 20 tabs and I want to load 1 image per each header. How can I do that?

**Comment by nimaa77** [comment]
Hi
Try This:

`        mViewPager.setMaterialViewPagerListener(new MaterialViewPager.Listener() {
            @Override
            public HeaderDesign getHeaderDesign(int page) {
                switch (page) {
                    case 0:
                        return HeaderDesign.fromColorAndUrl(
                                color,
                             "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png");
                    case 1:
                        return HeaderDesign.fromColorAndUrl(
                                color,
                                "url"
                //execute others actions if needed (ex : modify your header logo)
                return null;
            }
        });
`
