### ISSUE TITLE
Dark halo for Image background

### ISSUE THREAD

**Issue by quentin41500** [florent37/MaterialViewPager#30]
Could you please provide a way to display an halo over the background image ?
Some images I'm using are bright, and my header and tabs are not always visible.

**Comment by florent37** [comment]
You can set your own header layout with `app:viewpager_header`, so you can already do it :+1: 

My default header layout is 
	<?xml version="1.0" encoding="utf-8"?>
	<com.github.florent37.materialviewpager.MaterialViewPagerImageHeader
	    xmlns:android="http://schemas.android.com/apk/res/android"
	    android:id="@id/materialviewpager_imageHeader"
	    android:layout_width="match_parent"
	    android:layout_height="match_parent"
	    android:adjustViewBounds="true"
	    android:scaleType="centerCrop" />


So you can create (for sample)

	<?xml version="1.0" encoding="utf-8"?>
	<FrameLayout
		xmlns:android="http://schemas.android.com/apk/res/android"
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		>
		<com.github.florent37.materialviewpager.MaterialViewPagerImageHeader
		    android:id="@id/materialviewpager_imageHeader"
		    android:layout_width="match_parent"
		    android:layout_height="match_parent"
		    android:adjustViewBounds="true"
		    android:scaleType="centerCrop" />

		<YOUR_HALO/>

	</FrameLayout>

**Comment by quentin41500** [comment]
Thanks a lot
