### ISSUE TITLE
Issue with scrolling

### ISSUE THREAD

**Issue by hatamiarash7** [florent37/MaterialViewPager#308]
hi

i don't want use RecyclerView and i want just have two CardView in my layout
but i have some problems with scrolling  ..... header can't move like default and layout move over that like this : 

![screenshot_2017-04-11-23-26-43](https://cloud.githubusercontent.com/assets/16325641/24925867/e53fa09c-1f0e-11e7-8443-aef8f560d644.png)

how can i make a layout like original sample

![screenshot_2017-04-11-23-26-03](https://cloud.githubusercontent.com/assets/16325641/24925892/f3562e3a-1f0e-11e7-9531-b6989507f289.png)

and this is my xml file : 

<?xml version="1.0" encoding="utf-8"?>
    <com.github.ksoichiro.android.observablescrollview.ObservableScrollView
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:id="@+id/scrollView"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
    
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">
    
            <include layout="@layout/material_view_pager_placeholder"/>
    
            <android.support.v7.widget.CardView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginBottom="@dimen/cardMarginVertical"
                android:layout_marginLeft="@dimen/cardMarginHorizontal"
                android:layout_marginRight="@dimen/cardMarginHorizontal"
                android:layout_marginTop="@dimen/cardMarginVertical"
                android:background="@android:color/white"
                app:cardElevation="4dp"
                app:contentPaddingBottom="10dp"
                app:contentPaddingLeft="5dp"
                app:contentPaddingRight="5dp"
                app:contentPaddingTop="10dp">
    
                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:gravity="center_horizontal"
                    android:orientation="vertical">
    
                    <helper.PersianTextView
                        android:id="@+id/name"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:gravity="center"
                        android:text="نام"
                        android:textColor="#000"
                        android:textSize="20sp"
                        android:textStyle="normal|bold"/>
    
                    <helper.PersianTextView
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginTop="12dp"
                        android:gravity="center"
                        android:text="توضیحات"
                        android:textColor="#000"
                        android:textSize="18sp"
                        android:textStyle="normal|bold"/>
    
                    <helper.PersianTextView
                        android:id="@+id/description"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:gravity="center"
                        android:text="TextView"
                        android:textColor="@color/gray3"/>
    
                    <View
                        android:layout_width="match_parent"
                        android:layout_height="0.5dp"
                        android:layout_marginBottom="8dp"
                        android:layout_marginEnd="40dp"
                        android:layout_marginLeft="40dp"
                        android:layout_marginRight="40dp"
                        android:layout_marginStart="40dp"
                        android:layout_marginTop="8dp"
                        android:background="#FFDDDDDD"/>
    
                    <helper.PersianTextView
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:gravity="center"
                        android:text="ساعت کاری"
                        android:textColor="#000"
                        android:textSize="18sp"
                        android:textStyle="normal|bold"/>
    
                    <helper.PersianTextView
                        android:id="@+id/time"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:gravity="center"
                        android:text="TextView"
                        android:textColor="@color/gray3"/>
    
                    <View
                        android:layout_width="match_parent"
                        android:layout_height="0.5dp"
                        android:layout_marginBottom="8dp"
                        android:layout_marginEnd="40dp"
                        android:layout_marginLeft="40dp"
                        android:layout_marginRight="40dp"
                        android:layout_marginStart="40dp"
                        android:layout_marginTop="8dp"
                        android:background="#FFDDDDDD"/>
    
                    <helper.PersianTextView
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:gravity="center"
                        android:text="هزینه ارسال"
                        android:textColor="#000"
                        android:textSize="18sp"
                        android:textStyle="normal|bold"/>
    
                    <helper.PersianTextView
                        android:id="@+id/send_price"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:gravity="center"
                        android:text="TextView"
                        android:textColor="@color/gray3"/>
    
                    <View
                        android:layout_width="match_parent"
                        android:layout_height="0.5dp"
                        android:layout_marginBottom="8dp"
                        android:layout_marginEnd="40dp"
                        android:layout_marginLeft="40dp"
                        android:layout_marginRight="40dp"
                        android:layout_marginStart="40dp"
                        android:layout_marginTop="8dp"
                        android:background="#FFDDDDDD"/>
    
                    <helper.PersianTextView
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:gravity="center"
                        android:text="حداقل سفارش"
                        android:textColor="#000"
                        android:textSize="18sp"
                        android:textStyle="normal|bold"/>
    
                    <helper.PersianTextView
                        android:id="@+id/min_price"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:gravity="center"
                        android:text="TextView"
                        android:textColor="@color/gray3"/>
                </LinearLayout>
            </android.support.v7.widget.CardView>
    
            <android.support.v7.widget.CardView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginBottom="@dimen/cardMarginVertical"
                android:layout_marginLeft="@dimen/cardMarginHorizontal"
                android:layout_marginRight="@dimen/cardMarginHorizontal"
                android:layout_marginTop="@dimen/cardMarginVertical"
                android:background="@android:color/white"
                app:cardElevation="4dp"
                app:contentPaddingBottom="10dp"
                app:contentPaddingLeft="5dp"
                app:contentPaddingRight="5dp"
                app:contentPaddingTop="10dp">
    
                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:gravity="center_horizontal"
                    android:orientation="vertical">
    
                    <helper.PersianTextView
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:gravity="center"
                        android:text="آدرس"
                        android:textColor="#000"
                        android:textSize="18sp"
                        android:textStyle="normal|bold"/>
    
                    <helper.PersianTextView
                        android:id="@+id/address"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:gravity="center"
                        android:text="TextView"
                        android:textColor="@color/gray3"/>
    
                    <com.google.android.gms.maps.MapView
                        android:id="@+id/map"
                        android:name="com.google.android.gms.maps.MapFragment"
                        android:layout_width="match_parent"
                        android:layout_height="150dp"
                        android:layout_marginTop="12dp"
                        app:mapType="normal"
                        app:uiCompass="false"
                        app:uiRotateGestures="true"
                        app:uiScrollGestures="true"
                        app:uiTiltGestures="false"
                        app:uiZoomControls="false"
                        app:uiZoomGestures="true"
                        tools:ignore="MissingPrefix"/>
                </LinearLayout>
            </android.support.v7.widget.CardView>
        </LinearLayout>
    </com.github.ksoichiro.android.observablescrollview.ObservableScrollView >

**Comment by hatamiarash7** [comment]
I solved by moving adding method MaterialViewPagerHelper.register....(...) to onViewCreated

**Comment by chnouman** [comment]
@hatamiarash7  i'm having same problem can you please help me?

**Comment by hatamiarash7** [comment]
@chnouman you should move your register method to `onViewCreated()`

**Comment by chnouman** [comment]
ok @hatamiarash7  thanks for your time let me try this.
