### ISSUE TITLE
Header cant scroll down when switching Tab and Recyclerview has not enough elements to scroll

### ISSUE THREAD

**Issue by borgwald** [florent37/MaterialViewPager#31]
Hello,

the Problem is that the ObservableScrollView/Recyclerview in one Fragment remains in its position if there is not enough content in the Recyclerview to scroll, while another Recyclerview is scrolled in another Fragment. Therefore the Header cant be scrolled down again when switching Fragments. This leads to the next Problem: there is a big gap between header and content.

**Comment by florent37** [comment]
Yes, it's a known issue, but how can a scroller scroll when it has no enough content ?
I don't have a solution yet...

**Comment by borgwald** [comment]
maybe you can dynamically add a footer in your recyclerviewadapter?

**Comment by florent37** [comment]
Yes it's an option, but some people will throw issue with this footer...

2015-05-21 11:00 GMT+02:00 borgwald <notifications@github.com>:
