### ISSUE TITLE
ViewPager Title is not complete

### ISSUE THREAD

**Issue by kumarkeviv** [florent37/MaterialViewPager#313]
Hi Guys

First of all, thank you so much for great efforts.

Recently I noticed that when we use this "Material View Pager" in Android N the title of TAB's are not coming as full name as it was coming in previous versions of Android.

Does anyone has any fix or suggestion to overcome this.

Also attached the copy of the screenshot on Android N.
![screenshot_20170509-131335](https://cloud.githubusercontent.com/assets/17118240/25848340/40eceec0-34ba-11e7-8d4a-9b6ce35c1086.png)

**Comment by ricardocatarinoaltran** [comment]
Same problem here.
The solution was to create a tab bar, just like in the description
[https://github.com/florent37/MaterialViewPager#or-create-your-own-tab-bar](url)

and then put the `app:pstsPaddingMiddle="false"`
