### ISSUE TITLE
The UI doesn't show on Galaxy S5

### ISSUE THREAD

**Issue by stefanionescu** [florent37/MaterialViewPager#318]
Hey devs,

I tried implementing the ViewPager in my app. I followed the instructions from the README, but instead of seeing the Toolbar, the ViewPager and the primary color on the screen, my screen is black (Attached image).

I'm targeting API 25. I use the theme described in the README for the Activity. Here is the XML for the screen: 

        <com.github.florent37.materialviewpager.MaterialViewPager
          android:layout_width="match_parent"
          android:layout_height="match_parent"
          android:id="@+id/materialViewPager"
          app:viewpager_logo="@layout/header_logo"
          app:viewpager_logoMarginTop="100dp"
          app:viewpager_color="@color/colorPrimary"
          app:viewpager_headerHeight="200dp"
          app:viewpager_headerAlpha="1.0"
          app:viewpager_hideLogoWithFade="false"
          app:viewpager_hideToolbarAndTitle="false"
          app:viewpager_enableToolbarElevation="true"
          app:viewpager_parallaxHeaderFactor="1.5"
          app:viewpager_headerAdditionalHeight="20dp"
          app:viewpager_displayToolbarWhenSwipe="true"
          app:viewpager_transparentToolbar="true"
          app:viewpager_animatedHeaderImage="true"
          app:viewpager_disableToolbar="false"
          >

          </com.github.florent37.materialviewpager.MaterialViewPager>

     </RelativeLayout>

![18926620_2178915489001491_1750004039_o](https://cloud.githubusercontent.com/assets/15263515/26723428/2aa9b68e-479d-11e7-9219-7d9feca7b126.png)

**Comment by NobitaStudio** [comment]
me.too。My Api is 23

**Comment by NobitaStudio** [comment]
do you deal with it?can you tell me how to deal with it.it has spend me lots of time to think it!...

**Comment by adelabd** [comment]
I Have exactly the same problem ... My api is 25

**Comment by jennyqujy** [comment]
Same problem. Tried api 21 and 26

**Comment by wen-yuan-zhang** [comment]
Me too. My Android Studio is 3.6 and API is 29.
