### ISSUE TITLE
Some bugs in theme, header and list (video)

### ISSUE THREAD

**Issue by thaiduy** [florent37/MaterialViewPager#37]
When I implement your library to my project, I found some bugs and since I use maven link, I think it should be fixed from the library itself.

Here is a video in which I reproduced them: https://youtu.be/m9G9UN0p5ng

* 1: (0:0 - 0:17) Strange behaviour of theme: when the app is loaded the first time, the toolbar is placed __behind__ the statusbar thus being covered by the statusbar (notice the position of toolbar's buttons). But when rotate the screen, the toolbar is placed **below** the statusbar. It should be place below the statusbar at the first time. Not sure if it's because of my project or the library.

* 2: (0:17 - 0:36) When I scroll up in a page, then swipe to next few pages, then I scroll down again so the header can be shown fully, I swipe back to previous page, then I can see the strange position of the list.

![screenshot_2015-05-26-15-07-05](https://cloud.githubusercontent.com/assets/546798/7808613/c23b593c-03be-11e5-897e-000c84ffcdc7.png)

* 3: (0:36 - 0:50) Again when I scroll up, there's a chance that in some pages the list will not be scroll thus leaving a white space above the list.

![screenshot_2015-05-26-15-25-04](https://cloud.githubusercontent.com/assets/546798/7808704/59b0533a-03bf-11e5-8ee4-eabe3c0b8f77.png)

I can send you the source of my project if you want.

**Comment by florent37** [comment]
Yes, I know where it comes from.
In my sample I used only 4 tabs, and set the viewpager offset to '. So the fragments/Recyclers will not be destroyed/recreated.
In your case you use 100 tabs, so when you scroll to tab 95, the 98 and 99 will be destroyed. So the Recyclerview will be scrolled at 0

**Comment by florent37** [comment]
I'll try to fix it in the next release :wink:

**Comment by thaiduy** [comment]
Thank you :smiley:

**Comment by florent37** [comment]
okey I fixed it, can you try the 1.0.4.1 and tell me if it works :+1: 

    com.github.florent37:materialviewpager:1.0.4.1@aar
