### ISSUE TITLE
Header View stay hidden when i remove last item of RecyclerView

### ISSUE THREAD

**Issue by GrayaMax** [florent37/MaterialViewPager#38]
Hello,
I use MaterialViewPager with RecyclerView, everything is ok, but when i try to remove an item from my recycler adapter (generally the last), i cant see the header view anymore. When i scroll to top after item removed, the header view stays collapsed and i dont know why.

Can you help me ?

**Comment by florent37** [comment]
can you share me your code please ?

**Comment by GrayaMax** [comment]
```java
Set MaterialViewPager :

mMaterialViewPager = (MaterialViewPager) getActivity().findViewById(R.id.materialViewPager);
mMaterialViewPager.getToolbar().setVisibility(View.GONE);

mPagerAdapter = new ProfilFeedPagerAdapter(getActivity().getSupportFragmentManager(), getActivity(), mIdUser);

mViewPager = mMaterialViewPager.getViewPager();
mViewPager.setAdapter(mPagerAdapter);

mMaterialViewPager.getPagerTitleStrip().setViewPager(mViewPager);


MaterialViewPager in xml :

 <MaterialViewPager
        android:id="@+id/materialViewPager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:viewpager_logo="@layout/header_viewpager_profil_logo"
        app:viewpager_color="@color/BackgoundColor"
        app:viewpager_hideLogoWithFade="true"
        app:viewpager_headerHeight="150dp"
        app:viewpager_parallaxHeaderFactor="1.5"
        app:viewpager_logoMarginTop="20dp"
        app:viewpager_headerAlpha="1.0"
        app:viewpager_pagerTitleStrip="@layout/pager_sliding_tab_profil"
        />


Fragment in view pager :

 @Override
    public void onActivityCreated(Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);

        final LinearLayoutManager layoutManager = new LinearLayoutManager(getActivity());
        layoutManager.setOrientation(LinearLayoutManager.VERTICAL);


        
        mRecyclerView = (RecyclerView) mRootView.findViewById(R.id.recycler_view);
        mRecyclerView.setLayoutManager(layoutManager);
        mRecyclerView.setItemAnimator(new SlideInLeftAnimator());
        mEndlessRecyclerScrollListener = new AkEndlessRecyclerScrollListener(layoutManager) {
            @Override
            public void onLoadMore(int page) {
                if(!mIsTheEnd)
                    requestFeed();
            }
        };
        mRecyclerView.setOnScrollListener(mEndlessRecyclerScrollListener);
        mAdapter = new FeedVideoListAdapter(getActivity(), mDubList);
        mAdapter.setFeedVideoClickListener((MainActivity) getActivity());
        mAdapter.setFeedVideoAddRemoveListener(new FeedVideoListAdapter.FeedVideoAddRemoveListener() {
            @Override
            public void onVideoRemove(Dub dubSelected) {
                removeDubFromList(dubSelected);
             }
        });
        mMaterialAdapter = new RecyclerViewMaterialAdapter(mAdapter);
        mRecyclerView.setAdapter(mMaterialAdapter);
        MaterialViewPagerHelper.registerRecyclerView(getActivity(), mRecyclerView, mEndlessRecyclerScrollListener);

        
    }


    private void removeDubFromList(Dub dubSelected) {
        int count = mDubList.size();
        for (int i = 0; i < count; i++){
            if(dubSelected.stamp.contentEquals(mDubList.get(i).stamp)){
                mDubList.remove(i);
                mRecyclerView.getAdapter().notifyItemRemoved(i + 1);
                i = count;
            }
        }

```

**Comment by GrayaMax** [comment]
I think it's because sometimes when you remove an item, the recycler view collapse from top and scroll the content, but the onScrolled from MateriaViewPagerAnimator -> registerRecyclerView is not called.

**Comment by florent37** [comment]
I thinks it's because you remove the item in your adapter, and my
MaterialRecyclerAdapter isn't notified

2015-05-26 13:59 GMT+02:00 GrayaMax <notifications@github.com>:

**Comment by GrayaMax** [comment]
I remove from your adapter : 
```java
mMaterialAdapter = new RecyclerViewMaterialAdapter(mAdapter);
mRecyclerView.setAdapter(mMaterialAdapter);
```
so mRecyclerView.getAdapter() = RecyclerViewMaterialAdapter in

```java
 mRecyclerView.getAdapter().notifyItemRemoved(i + 1);
```

**Comment by florent37** [comment]
can you try to remove my adapter, and create a header in yours

in row 0 use

    view = LayoutInflater.from(parent.getContext())
                        .inflate(R.layout.material_view_pager_placeholder, parent, false);
                return new RecyclerView.ViewHolder(view) {
                };

like my adapter
https://github.com/florent37/MaterialViewPager/blob/master/materialviewpager/src/main/java/com/github/florent37/materialviewpager/adapter/RecyclerViewMaterialAdapter.java

so your delete/add operations will works !

**Comment by GrayaMax** [comment]
The delete and add operations already work, the problem is the "Autoscroll" of these operations isn't triggered by the onScrollListener in the method registerRecyclerView :(

**Comment by florent37** [comment]
as said in the readme, you have to add the callback on the
MaterialViewPagerHelper, because I already use it on the MaterialViewPager

MaterialViewPagerHelper.registerRecyclerView(getActivity(),
mRecyclerView, myRecyclerViewOnScrollListener);

https://github.com/florent37/MaterialViewPager#reyclerviewonscrolllistener

2015-05-26 17:44 GMT+02:00 GrayaMax <notifications@github.com>:

**Comment by GrayaMax** [comment]
I found a way to fix my problem, i replace your scrollY += dy; in 
MaterialViewPagerAnimator -> registerRecyclerView
by

scrollY = recyclerView.computeVerticalScrollOffset();

and it works well, if you remove all item in the recyclerview with removeItem the header extend :)

**Comment by florent37** [comment]
nice work :D can you send me a pull request so I will add it in the next
release ? please :)

2015-05-27 14:13 GMT+02:00 GrayaMax <notifications@github.com>:

**Comment by GrayaMax** [comment]
i never do it before ^^ i will try ^^ But i think i have some work to do because when you remove an item who make the recyclerview not enough long to be scrolled the header and the pageIndicatorStrip appear and move not smoothly (instant whit no animation) :( and its not really beautiful. I will notify you when I have succeeded to do something great :)
