### ISSUE TITLE
pull-up loads

### ISSUE THREAD

**Issue by guoyoujin** [florent37/MaterialViewPager#39]
Hello, I want to use in this project the drop-down refresh, pull-up loads more can be achieved, can you help me

**Comment by florent37** [comment]
you want to use SwipeRefreshLayout ?

**Comment by guoyoujin** [comment]
yes,Can this project combines SwipeRefreshLayout to use it, I don't know how to realize the drop-down refresh, you can help me, thank you

**Comment by florent37** [comment]
I did this on a tutorial : http://tutos-android-france.com/ajouter-un-pull-to-refresh-avec-swiperefreshlayout/
it's in french but you can read java & xml 

    <android.support.v4.widget.SwipeRefreshLayout
        android:id="@+id/swipeRefreshLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
 
        <androud.support.v4.widget.RecyclerView
            android:id="@+id/recyclerView"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
 
    </android.support.v4.widget.SwipeRefreshLayout>



    mSwipeRefreshLayout = (SwipeRefreshLayout) findViewById(R.id.swipeRefreshLayout);
        mSwipeRefreshLayout.setOnRefreshListener(this);


    @Override
    public void onRefresh() {
    	//your code
    }

**Comment by guoyoujin** [comment]
Thank you, I'm trying to put you said embedded in, thank you for your answer, thank you very much!

**Comment by florent37** [comment]
don't hesitate :+1:
