### ISSUE TITLE
Fragment webview is not working properly 

### ISSUE THREAD

**Issue by pawarlalit29** [florent37/MaterialViewPager#41]
java.lang.NoSuchMethodError: android.webkit.WebView.evaluateJavascript at com.github.florent37.materialviewpager.MaterialViewPagerHelper.injectHeader(MaterialViewPagerHelper.java:141)
            at com.example.materialviewpager..fragments.WebViewFragment$1.onPageFinished(WebViewFragment.java:45)

in line number 45 this code is written 
      MaterialViewPagerHelper.injectHeader(mWebView, true);

**Comment by florent37** [comment]
Yes, I didn't want to waste time on WebViews, I don't like this component...

If you want you can create a pull request with the modifications, for >API10 and add loadUrl with javascript only if evaluateJavascript isn't available

http://stackoverflow.com/questions/19338999/android-js-in-webview-loadurl

**Comment by pawarlalit29** [comment]
thanks ...
