### ISSUE TITLE
Any way to remove tab indicator?

### ISSUE THREAD

**Issue by Hzawa** [florent37/MaterialViewPager#43]
I'm using this library with dynamic content. Sometimes the dynamic content means I only have one list (one fragment in pager adapter).

When there's only one fragment, the tab indicators don't make sense, so I'd like to hide them.

When I try to hide the tabs, it looks fine until this happens (on scroll back up):

![mvpproblem](https://cloud.githubusercontent.com/assets/11961290/7820842/6e0c7da4-03b0-11e5-93d8-ad7ba98a458b.png)

Maybe can you add option app:viewpager_pagerTitleStrip="none" and programmatic option as well for when there's only one list? I know observableScrollView library supports this so it should be fairly possible. Maybe some math is hard-coded for animations though, which might make this a bit more than setting a certain layout visibility to just gone.

**Comment by andreabeggiato-geekcups** [comment]
+1

**Comment by florent37** [comment]
hummm it's a huge work to remove the tabs...
I think it'll be easier to create a view without tabs and recreate the parallax effect, I send you a sample of application I made using this : 
https://github.com/florent37/Potier
