### ISSUE TITLE
Issue with webview

### ISSUE THREAD

**Issue by sach200** [florent37/MaterialViewPager#44]
Look the white background at the top of webview.. It is covering the backgorund set to viewpager.. Is this a bug?

![screenshot_2015-05-27-12-32-26 1](https://cloud.githubusercontent.com/assets/12546237/7830595/7e5f517e-046c-11e5-86bb-748f406a43e5.png)

**Comment by sach200** [comment]
Same thing happens when another link is opened in webview... It covers entire height and hence covers up the viewpager background

**Comment by florent37** [comment]
No it's not a bug. I have to get a full height scroller, so my only
solution is to make the background clear color and add a margin into the
top.
I really hate webviews, so I don't think i'm gonna modify this. But if you
have another solution you can create a pull request, I will merge it ;)

2015-05-27 9:08 GMT+02:00 sach200 <notifications@github.com>:

**Comment by sach200** [comment]
I added transparent background color and added margin at the top.. Got this!!!! The white rectangle doesnt scroll... Webview scrolls in half portion only
![screenshot_2015-05-27-13-46-18 1](https://cloud.githubusercontent.com/assets/12546237/7831699/d35d8a24-0476-11e5-8bb6-2b2c53840f13.png)

**Comment by florent37** [comment]
and add

webSettings.setRenderPriority(WebSettings.RenderPriority.HIGH); webSettings.
setCacheMode(WebSettings.LOAD_NO_CACHE); webSettings.setJavaScriptEnabled(
true); webSettings.setDomStorageEnabled(true); //transparent background
webView.setLayerType(WebView.LAYER_TYPE_SOFTWARE, null);

2015-05-27 10:18 GMT+02:00 sach200 <notifications@github.com>:

**Comment by florent37** [comment]
https://github.com/florent37/MaterialViewPager/blob/master/materialviewpager/src/main/java/com/github/florent37/materialviewpager/MaterialViewPagerHelper.java

2015-05-27 10:20 GMT+02:00 Florent Champigny <champigny.florent@gmail.com>:
