### ISSUE TITLE
Not working well with GridView or any other view inside of ObservalbeScrollView. plus how can we set icons to every tab?

### ISSUE THREAD

**Issue by DevendraSingh91** [florent37/MaterialViewPager#46]
@florent37  Wanted to make a gridView inside of ObservableScrollVeiw  i set up as your directions. but the griditems coming like another pages cardsview.  i wants a simple GridView. not popping towards the tabs. will send you snapshot soon. plus can we set status bar's color a bit likely the color for this fragment that you set in main activity.

**Comment by florent37** [comment]
You can use only one scroller per tab. Please use RecyclerView with GridLayoutManager instead of GridView.

you can find a sample here : 
http://blog.sqisland.com/2014/12/recyclerview-grid-with-header.html
