### ISSUE TITLE
How to add Icons to MaterialViewPager tabs?

### ISSUE THREAD

**Issue by DevendraSingh91** [florent37/MaterialViewPager#48]
Hi, Would you explain how can we add icon on every tab we creates?

**Comment by omidheshmatinia** [comment]
<com.github.florent37.materialviewpager.MaterialViewPager
...
        app:viewpager_logo="@layout/header_logo"
...
        />

and this is header_logo:

<?xml version="1.0" encoding="utf-8"?>
<ImageView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/logo_white"
    android:layout_width="@dimen/top_ViePager_Logo_Size"
    android:layout_height="@dimen/top_ViePager_Logo_Size"/>


at last in your adapter:
//called when the current page has changed
    @Override
    public void setPrimaryItem(ViewGroup container, int position, Object object) {
        super.setPrimaryItem(container, position, object);
       ....
        topIcon.setImageResource(topIcons[position]);
    }
topIcon is the header logo ImageView!

**Comment by DevendraSingh91** [comment]
will this add icons as i asked on stackoverflow.. 
http://stackoverflow.com/questions/30524866/how-can-i-add-icons-to-the-tabs-using-florent37-materialviewpager

**Comment by omidheshmatinia** [comment]
i taught you only want to change the LOGO
 you should implement your own sliding tab strip!!!!
i answer your question on stackoverflow

**Comment by DevendraSingh91** [comment]
please give me a code snippet for that. actually i am not so good. please.

**Comment by omidheshmatinia** [comment]
i post you the code!

**Comment by DevendraSingh91** [comment]
Thank you so much will let you know back
