### ISSUE TITLE
Fragment incorrect attached

### ISSUE THREAD

**Issue by Ne1c** [florent37/MaterialViewPager#52]
Fragment incorrect attached. All code i took from sample, but i don't now, where this bug can be.

Screenshot:
![screenshot_2015-05-31-23-30-25 1](https://cloud.githubusercontent.com/assets/5927051/7903714/8f2934a0-07ed-11e5-876d-701c0b89c99f.png)

Sorry, for my english

**Comment by florent37** [comment]
can you please send your fragment ?

it contains RecylcerView or ObservableScrollview ?

Did you try with my sample ?
