### ISSUE TITLE
Bring all resources under MVP namespace

### ISSUE THREAD

**Issue by sahildave** [florent37/MaterialViewPager#53]
The base theme in the library is AppTheme which collides with the AppTheme of the main app. Please bring these resources under MaterialViewPager namespace, for eg: MVP_AppTheme.

**Comment by sahildave** [comment]
This guy - https://github.com/florent37/MaterialViewPager/blob/master/materialviewpager/src/main/res/values/styles.xml#L8

**Comment by florent37** [comment]
yes, it's a great idea :+1: 
do you want to do it and submit a pull request ?
i can do it btw if you don't have time :wink:

**Comment by sahildave** [comment]
Hey @florent37 have you done it? Couldnt check the notifications during the weekend.

**Comment by maxbaldrighi** [comment]
Same problem.
Please can anyone provide the enhancement?
