### ISSUE TITLE
Please allow setImageFromFile()

### ISSUE THREAD

**Issue by jkwiecien** [florent37/MaterialViewPager#54]
I have image files stored locally and I wish I could set them on MaterialViewPager using some ```setImageFromFile()``` instead ```setImageUrl()```.

Could be nice if the method take screen width and logo height into account resizing the bitmap in case picture File was very large :)

**Comment by jkwiecien** [comment]
Or I guess I can use ```setImageDrawable()``` ...

**Comment by florent37** [comment]
yes, you can use `setImageDrawable()` :+1:
