### ISSUE TITLE
RecyclerView dataset change, the Placeholder should not show all

### ISSUE THREAD

**Issue by ares89** [florent37/MaterialViewPager#58]
Hi,florent,
I have RecyclerView in one pager
and the viewpager behaves sticky toolbar
I scroll the recyclerview to some position but not the start, so the placeholder is hide,
then I change the dataset and call the adapter notifyDataSetChanged().

the PlaceHolder in recycerview shows all its size,not part.

It should hide itself, and let the item under it adjust to the pagerstriptab.

thanks!

**Comment by florent37** [comment]
you have to call notifyDataSetChanged on the MaterialRecyclerAdapter and your Adapter.
I can't override the notifyDataSetChanged() of the MaterialRecyclerAdapter because it's declared as final...

**Comment by ares89** [comment]
thank you! this works~
