### ISSUE TITLE
Remove Picasso dependency

### ISSUE THREAD

**Issue by ppamorim** [florent37/MaterialViewPager#6]
Make it out of box.
Just add a callback to return the ImageView.

**Comment by florent37** [comment]
You think it's better to add just a getter to the imageview ?

It's an good idea, but I added the dependency for implementing directly the fading animation in the callback.

mViewPager.setImageUrl(imageUrl,fadeDuration);

how do you think we can proceed ?

**Comment by ppamorim** [comment]
I'll do it.

**Comment by florent37** [comment]
ok great :+1:
thanks for helping me improving MaterialViewPager, it's so cool

**Comment by ares89** [comment]
@ppamorim 
is there any news about this?
thanks
