### ISSUE TITLE
Add option to disable KenBurns effect

### ISSUE THREAD

**Issue by stephenmcbride** [florent37/MaterialViewPager#61]
Would be nice to have the option to disable the effect and expose the ImageView so the scale type can be set. Great library though, thanks for creating it!

**Comment by florent37** [comment]
it's already possible, you just have to replace the header by a layout containing only an imageview

     app:viewpager_header="@layout/myHeader"

myHeader.xml : 

    	<ImageView
	    xmlns:android="http://schemas.android.com/apk/res/android"
	    android:id="@id/materialviewpager_imageHeader"
	    android:layout_width="match_parent"
	    android:layout_height="match_parent"
	    android:adjustViewBounds="true"
	    android:scaleType="centerCrop" />

**Comment by stephenmcbride** [comment]
Of course! *smacks forehead* - thanks!

**Comment by florent37** [comment]
you think it would be usefull to add the option viewpager_withKenBurns="true | false" ?

**Comment by stephenmcbride** [comment]
I think it would be useful alright

**Comment by jkwiecien** [comment]
+1 to this

**Comment by florent37** [comment]
I already done this, but in the dev branch. I'll upload it tomorrow for you
;)

**Comment by jkwiecien** [comment]
Lovely, waiting!

**Comment by florent37** [comment]
done :)

    app:viewpager_animatedHeaderImage="false"

available in the 1.0.5.2 (I'll update the 1.0.6 when I'll fixed some bugs)

thanks guys :+1:
