### ISSUE TITLE
Attaching a ClickListener to the header picture

### ISSUE THREAD

**Issue by MarKco** [florent37/MaterialViewPager#62]
Hello,
I'd like to attach a ClickListener on the MaterialViewPager header picture, in order to start a gallery activity or anything else, but I couldn't find a way to do so. Is this already possible in this version? Theoretically it'd be enough to be able to retrieve the View and then attaching the listener to it, isn't it?

Cheers

**Comment by florent37** [comment]
the headerview is accessible by `findViewById(R.id.materialviewpager_imageHeader)`
so you can use

findViewById(R.id.materialviewpager_imageHeader).setOnClickListener(new View.OnclickListener(){
	public void onClick(View v){
		
	}
});

**Comment by MarKco** [comment]
Thank you Florent, but I actually can't make it work. I tried to do the following, in my activity's onCreate:

        final MaterialViewPagerImageHeader headerBackgroundImage = (MaterialViewPagerImageHeader) mViewPager.findViewById(R.id.materialviewpager_imageHeader);
        
        headerBackgroundImage.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Toast.makeText(HotelDetailsActivity.this, "prova", Utils.Toaster.LENGTH_SHORT).show();
            }
        });

The headerBackgroundImage gets filled with the right View object, or so it seems to me, but then the OnClick event is never reached :-/

Should I place the code somewhere else?

**Comment by MarKco** [comment]
Yep, I keptr trying with different configurations but it simply doesn't work. My guess (I can't prove it) is that the main layout covers somehow the picture.

I tried with adding a picture change:

                final MaterialViewPagerImageHeader headerBackgroundImage = (MaterialViewPagerImageHeader) mViewPager.findViewById(R.id.materialviewpager_imageHeader);

                headerBackgroundImage.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {
                        Toast.makeText(HotelDetailsActivity.this, "prova", Utils.Toaster.LENGTH_SHORT).show();
//                        finish();
                    }
                });

                headerBackgroundImage.setImageUrl("http://www.picturesnew.com/media/images/picture-wallpaper.jpg", 200);

The picture gets changed but the OnClickListener is never triggered.
