### ISSUE TITLE
Change text in header dynamically

### ISSUE THREAD

**Issue by diogo10** [florent37/MaterialViewPager#63]
Hello,

How can I do it ? My header_logo.xml is a TextView and I would like change the text in Java...Its possible ? I don't a method to do it....

**Comment by diogo10** [comment]
View view = mViewPager.getRootView() ;
        TextView title = (TextView) view.findViewById(R.id.logo_white);
        title.setText(option);


I found...thanks.

**Comment by softmarshmallow** [comment]
in my case

                                                                                   java.lang.RuntimeException: Unable to start activity `ComponentInfo{com.softmarshmallow.seoulhighschool/com.softmarshmallow.seoulhighschool.Views.SchoolIntoduction.SchoolIntroductionActivity}: java.lang.ClassCastException: android.support.v7.widget.AppCompatImageView cannot be cast to android.widget.TextView
`
