### ISSUE TITLE
When I change the tab and after return....the top disappears

### ISSUE THREAD

**Issue by diogo10** [florent37/MaterialViewPager#69]
And I need scroll to the top to see the top...is like the user scroll to the bottom. I didn't find issues similar...what I need do ?

**Comment by florent37** [comment]
Sorry I don't understant what you're trying to do

**Comment by florent37** [comment]
Can you please add detail, or video ?

**Comment by idragon81** [comment]
He means the header view is gone when scrolling and switching tabs, 
I faced this too when using recyclerview and switching tabs, but I'm no longer able to reproduce it. Maybe new version fixed it or setting viewpager offscreen limit not sure

**Comment by diogo10** [comment]
Yes @idragon81  this is correct. I cant reproduce @florent37 ....sorry about that. I am working in other project now.
