### ISSUE TITLE
android 2.3

### ISSUE THREAD

**Issue by croccio** [florent37/MaterialViewPager#7]
please support android 2.3 too

**Comment by florent37** [comment]
OkI will do this using ViewCompat and maybe NineOldAndroid, should be done rapidly

**Comment by croccio** [comment]
great :D

**Comment by ppamorim** [comment]
Don't support Android 2.3.

**Comment by ppamorim** [comment]
@florent37 Don't use NineOldAndroid. It was deprecated.

**Comment by florent37** [comment]
ok so 2.3 will not be supported.
It's less than 10% of the users https://developer.android.com/about/dashboards/index.html
