### ISSUE TITLE
icons not showing properly in MaterialTabhost.

### ISSUE THREAD

**Issue by DevendraSingh91** [florent37/MaterialViewPager#71]
I tried to added icons in the tab. but it is not showing properly.
I am adding images here.
![screenshot_2015-06-09-13-36-41 1](https://cloud.githubusercontent.com/assets/11460206/8053348/8a9de52c-0ead-11e5-9377-29ad7142324d.png)

![screenshot_2015-06-09-13-32-27 1](https://cloud.githubusercontent.com/assets/11460206/8053351/925117e4-0ead-11e5-9e40-b326b12cc3b5.png)

**Comment by TheGhoul21** [comment]
I tried to return a Spannable with ImageSpan in the getPageTitle() adapter's function, but with no luck.

**Comment by florent37** [comment]
please look at the https://github.com/jpardogo/PagerSlidingTabStrip readme
