### ISSUE TITLE
Adapter Shuffling images and layout colors.

### ISSUE THREAD

**Issue by DevendraSingh91** [florent37/MaterialViewPager#72]
Hi, used this and working fine but i tried to set random background color to parent layout to the adapter 's inflated layout , say the list_big_card.
but when i scrolls up and down the colors changes its position.
posting my adapter's code here.

public class TOAdapter extends RecyclerView.Adapter<TOAdapter.ViewHolder> {
    JSONArray jsonArray;
    private String title;
    private String image;
    private ImageLoader imageLoader;
    private String subtitle;
    private String subti;
    private Context context;
    private ImageView clip;

    public TOAdapter(JSONArray jsonArray) {
        this.jsonArray = jsonArray;
    }

    // Create new views (invoked by the layout manager)
    @Override
    public TOAdapter.ViewHolder onCreateViewHolder(final ViewGroup parent,
                                                   int viewType) {
        // create a new view
        View itemLayoutView = LayoutInflater.from(parent.getContext())
                .inflate(R.layout.top_twenty_list, parent, false);
        final ViewHolder viewHolder = new ViewHolder(itemLayoutView);

        return viewHolder;
    }

    // Replace the contents of a view (invoked by the layout manager)
    @Override
    public void onBindViewHolder(final ViewHolder viewHolder, int position) {

        // - get data from your itemsData at this position
        // - replace the contents of the view with that itemsData
        // myTypeface = Typeface.createFromAsset(context.getAssets(), "fonts/RobotoCondensedBoldItalic.ttf");
        int color = generateRandomColor();
        //viewHolder.frame.setBackgroundColor(color);
        viewHolder.layer.setBackgroundColor(color);
        try {
            JSONObject obj = jsonArray.getJSONObject(position);
            title = obj.getString("title");
            image = obj.getString("brand_logo");
            subtitle = obj.getString("sub_title");
        } catch (JSONException e) {
            e.printStackTrace();
        }
        viewHolder.txtViewTitle.setText(subtitle);
        viewHolder.subtitle.setText(title);

        if (imageLoader == null)
            imageLoader = AppController.getInstance().getImageLoader();
        String full_Url = "http://savepocketmoney.algonation.com/assets/upload/offer/" + image;
        viewHolder.thumbnail.setImageUrl(full_Url, imageLoader);
        viewHolder.btn_get_deal.setTag(position);

        viewHolder.btn_get_deal.setOnClickListener(new View.OnClickListener() {
            public JSONObject obj;
            public ArrayList<String> offerlist = new ArrayList();

            @Override
            public void onClick(View view) {

                Intent offerpage = new Intent(AppController.getInstance().getApplicationContext(), OfferDetails.class);
                Integer pos = (Integer) view.getTag();
                try {
                    obj = jsonArray.getJSONObject(pos);
                    offerpage.putExtra("jsonObj", obj.toString());

                } catch (JSONException e) {
                    e.printStackTrace();
                }

                //offerpage.getParcelableArrayListExtra(offerlist);
                offerpage.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                AppController.getInstance().getApplicationContext().startActivity(offerpage);
            }
        });
        viewHolder.clip.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                int iColor = Color.parseColor("#0000FF");

                int red = (iColor & 0xFF0000) / 0xFFFF;
                int green = (iColor & 0xFF00) / 0xFF;
                int blue = iColor & 0xFF;

                float[] matrix = {0, 0, 0, 0, red
                        , 0, 0, 0, 0, green
                        , 0, 0, 0, 0, blue
                        , 0, 0, 0, 1, 0};

                ColorFilter colorFilter = new ColorMatrixColorFilter(matrix);
                clip.setColorFilter(colorFilter);
            }
        });

        //viewHolder.txtViewTitle.setTypeface(myTypeface);

    }

    // inner class to hold a reference to each item of RecyclerView
    public static class ViewHolder extends RecyclerView.ViewHolder {

        private final NetworkImageView thumbnail;
        //private final RelativeLayout frame;
        private final RelativeLayout layer;
        public TextView txtViewTitle;
        public TextView subtitle;
        public ImageView clip;
        public MaterialRippleLayout btn_get_deal;

        public ViewHolder(View itemLayoutView) {
            super(itemLayoutView);
            txtViewTitle = (TextView) itemLayoutView.findViewById(R.id.txttitle_toptwenty);
            subtitle = (TextView) itemLayoutView.findViewById(R.id.sub_title_toptwenty);
            thumbnail = (NetworkImageView) itemLayoutView.findViewById(R.id.thumbnail_topwenty);
            //frame = (RelativeLayout) itemLayoutView.findViewById(R.id.frame);
            layer = (RelativeLayout) itemLayoutView.findViewById(R.id.layer);
            btn_get_deal = (MaterialRippleLayout) itemLayoutView.findViewById(R.id.ripple);
            clip = (ImageView) itemLayoutView.findViewById(R.id.ic_clip);

        }

    }

    // Return the size of your itemsData (invoked by the layout manager)
    @Override
    public int getItemCount() {
        return jsonArray.length();
    }

    final Random mRandom = new Random(System.currentTimeMillis());

    public int generateRandomColor() {
        // This is the base color which will be mixed with the generated one
        final int baseColor = Color.WHITE;

        final int baseRed = Color.red(baseColor);
        final int baseGreen = Color.green(baseColor);
        final int baseBlue = Color.blue(baseColor);

        final int red = (baseRed + mRandom.nextInt(256)) / 2;
        final int green = (baseGreen + mRandom.nextInt(256)) / 2;
        final int blue = (baseBlue + mRandom.nextInt(256)) / 2;

        return Color.rgb(red, green, blue);
    }
}

**Comment by florent37** [comment]
it's because your views are recycled. generateRandomColor is called each time a cell become visible, even if it was before on screen

**Comment by florent37** [comment]
try to generate the color from depending on your cell position :+1:

**Comment by DevendraSingh91** [comment]
I resolved it doing some changes in adapter like creating model class etc.
