### ISSUE TITLE
Add apt support

### ISSUE THREAD

**Issue by jkwiecien** [florent37/MaterialViewPager#77]
Library won't build if the app uses apt plug-in. 

That means no Dagger or Dagger2 for us.

**Comment by paxxux** [comment]
Well, I use apt with AndroidAnnotiations and it builds without any problems. 

classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'

**Comment by florent37** [comment]
Anyone have issue with Apt too ?

**Comment by jkwiecien** [comment]
I'll reinvestigate it today.

**Comment by jkwiecien** [comment]
Reinvestigation indicates that it was some kind of anomaly (many of those in AS novadays :/)

No more problems with apt.
