### ISSUE TITLE
How to get SearchView to work?

### ISSUE THREAD

**Issue by devkhan** [florent37/MaterialViewPager#80]
I mean, I have setup everything required for SearchView to work, but it just doesn't work.

The official guide is here: 

http://developer.android.com/training/search/setup.html

But, since you completely override the default toolbar, I think there must be some other way to make it work. Also, I am implementing MaterialViewPager inside a Fragment. The SearchView doesn't even expand as it does normally. Can you help me out, please?

**Comment by florent37** [comment]
did you set the toolbar as support actionbar ?

**Comment by devkhan** [comment]
Yes, I have done that. Plus when I try to implement the SearchView inside onCreateOptionsMenu() in the fragment, it never reaches there, i.e. I do not see logging info even after setting log in that function. I also thought of implementing it inside MainActivity hoping it would be inherited by the fragment, but I don't see logging info on any of those.

**Comment by florent37** [comment]
can you please send me your code ? (sorry for the delay)
