### ISSUE TITLE
Some PagerSlidingTabStrip properties aint working anymore

### ISSUE THREAD

**Issue by Karolina90** [florent37/MaterialViewPager#81]
Properties from custom tabs that were working in 1.0.4:

```app:pstsTextAllCaps="true"
    app:pstsTextColorSelected="@color/white"
```

Now:
```
Error:(2) No resource identifier found for attribute 'pstsTextAllCaps' in package ...
Error:(2) No resource identifier found for attribute 'pstsTextColorSelected' in package ...
```

**Comment by florent37** [comment]
it's a PagerSlidingTabStrip issue, please refer to the official Readme : https://github.com/jpardogo/PagerSlidingTabStrip

or send the issue to https://github.com/jpardogo/PagerSlidingTabStrip/issues

**Comment by CelticParser** [comment]
See: https://github.com/jpardogo/PagerSlidingTabStrip/pull/70#issuecomment-115391767
