### ISSUE TITLE
Enhancement : Set color of Viewpager header and toolbar using dominant color of image

### ISSUE THREAD

**Issue by idragon81** [florent37/MaterialViewPager#82]
Like some Android apps, say for example Whatsapp, the color is set based on the dominant colors of the image,  like the profile picture in Whatsapp profile Info. 

I've achieved this by creating an interface between MaterialViewPager and MaterialViewPagerImageHeader and by passing the bitmap from imageviewheader to Palette support library by google.

**Comment by florent37** [comment]
Yes it's possible with the Palette :+1: 

The developpers can do it but I don't think all the projects have to do it, the best would be to just create a Gist as free open-source code

**Comment by idragon81** [comment]
In that case I think setting a callback for when them image is loaded exposing the imageview could be helpful, because right now I've manually set it up using Picasso's callback

**Comment by florent37** [comment]
Yes, that'll be a good option. I'll add it into the next release ;)

**Comment by idragon81** [comment]
Thanks buddy,
Appreciate your work. Great library BTW 👍
