### ISSUE TITLE
Custom view header

### ISSUE THREAD

**Issue by hongzhou85** [florent37/MaterialViewPager#87]
Can this work with a custom view header instead of just image view as background in the header?

**Comment by roideuniverse** [comment]
Most likely yes. referring the readme: `app:viewpager_logo="@layout/header_logo" <-- look custom logo layout`

**Comment by florent37** [comment]
Yes, or `app:viewpager_logo="@layout/viewpager_header" <-- look custom background header layout`

**Comment by hongzhou85** [comment]
![screenshot_2015-06-24-16-40-46](https://cloud.githubusercontent.com/assets/4978166/8325965/19fe95de-1a90-11e5-8049-24e7ae7f9dc6.png)

Hi florent37, I'm trying to insert the view pager into a fragment instead of activity. Above is the first attempt.
As I have been using PageSlidingTabStrip, I'm using that instead, to avoid build issues with duplicate library. the Recycler view is filling the whole height instead of underneath the tab and the tab is out of place.

The layout for the view:
https://gist.github.com/hongzhou85/3646d9bc909028260d8d
