### ISSUE TITLE
Pull to Refresh/Endless Scroll and Remote Data

### ISSUE THREAD

**Issue by willysharp5** [florent37/MaterialViewPager#88]
This is more a question than a bug. Is there a way to implement a navigation drawer as well as use a RecyclerView to show the data on the cards which would allow for pull to refresh, endless scroll and an ItemClick on individual cards to show more details. 

Am am somewhat new to Andriod so if yo could point me to how this can be achieved using your library or shoot over some sample code. 

Thanks

**Comment by florent37** [comment]
Yes you can, just listen to the scroll of your recyclerview to implement endless scroll, and add a SwipeRefreshLayout to enable PullToRefresh

**Comment by florent37** [comment]
http://tutos-android-france.com/ajouter-un-pull-to-refresh-avec-swiperefreshlayout/
