### ISSUE TITLE
Anything Holding it back from Lower API

### ISSUE THREAD

**Issue by frostymarvelous** [florent37/MaterialViewPager#9]
Hi, I find this really nice, but was just wondering what special things are holding it back from working on a lower api, maybe 11.

If they aren't that critical, I'm interested in working on making it work on a lower api.

**Comment by florent37** [comment]
We could use ViewCompat for the setY & setTranslationY, X ...

But now MaterialViewPager is deprecated :cry: so I don't really want to import it in the library

https://github.com/JakeWharton/NineOldAndroids/

**Comment by frostymarvelous** [comment]
O okay, so nineoldandroids will work fine.
Anyway, I believe it is stable enough and has no issues.
Mainly, Jake's issue is to force devs to start developing for newer API's rather than always backporting.
It is true that most users now use newer versions of android, but for us in Africa and I believe india, api 9 is a reality we have to deal with everyday.

Maybe, I'll just fork it so the project can continue to remain awesome and focus on the newer users. Thanks a bunch!
