### ISSUE TITLE
How to make a layout like this one in Spotify?  

### ISSUE THREAD

**Issue by jjvargas** [florent37/MaterialViewPager#97]
It looks like the Shuffle Play Green Button is like a Sticky header,  any ideas???

![spotify](https://cloud.githubusercontent.com/assets/1838805/8502996/ce747396-21af-11e5-9195-acf266a2ecee.jpg)

**Comment by florent37** [comment]
It's just a parallax effect, check out this project I made :
https://github.com/florent37/Potier

play with setTranslationY while listening to the Recyclerview.Scroll

https://github.com/florent37/Potier/blob/master/app/src/main/java/com/github/florent37/xebia/home/parallax/ParallaxHelper.java

2015-07-03 19:19 GMT+02:00 Javier Vargas <notifications@github.com>:

**Comment by jjvargas** [comment]
It's the Parallax plus the Shuffle Play Button staying on top as a Sticky Header  I checked your sample but it just has the Parallax Effect .   

I just found this article that describes a bit this  :)
https://armijnvink.wordpress.com/2014/05/27/spotify-scrolling-effect-2014/
