### ISSUE TITLE
Added the MaterialViewpager in a fragment, How do i remove the arrow?

### ISSUE THREAD

**Issue by amith2151** [florent37/MaterialViewPager#98]
pretty much tried everything to remove the arrow. since i call the toolbar in the activity and not the fragment there's no way to hide that arrow.
help?
![capture](https://cloud.githubusercontent.com/assets/13176874/8507991/0f1e4e24-227a-11e5-9371-7dc1b8af047a.PNG)

**Comment by florent37** [comment]
did you try to hide the toolbar from matetrialviewpager ?
matetrialviewpager.getToolbar().setVisibility(GONE)

**Comment by amith2151** [comment]
i cant use materialviewpager.getToolbar() for some reason, i always get a null object reference error. i got the toolbar in the MainActivity using the findViewbyid option

**Comment by dankolesnikov** [comment]
Amith,

Could you please upload your code how you figured out to use a library within a fragment?
I am having a hard time to do it.

Thanks!
Dan

**Comment by amith2151** [comment]
hi Dan, i used the MaterialPageViewer just as any other layout in the fragment. just create an xml with this viewpager and call it in a fragment. away from my computer at the moment but i will upload the code if you still need some help.

**Comment by munimisu** [comment]
Hi Amith,
I am trying to do the same, add the viewPager in fragment, and dead stuck on it. A snippet would be very helpful. 

Thanks in advance!

**Comment by FuriousLlama** [comment]
My solution was to leave the fragment with the materialviewpager without any other toolbar and add a toolbar to the other fragments.

Then on the creation of the view on the fragment that contains the materialviewpager instance just hook up the its toolbar with the one supplied by the activity:

`@Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        super.onCreate(savedInstanceState);

        mViewPager = (MaterialViewPager) getActivity().findViewById(R.id.materialViewPager);

        ...

        AppCompatActivity hostActivity = (AppCompatActivity) getActivity();

        Toolbar toolbar = mViewPager.getToolbar();
        hostActivity.setSupportActionBar(toolbar);
        final ActionBar actionBar = hostActivity.getSupportActionBar();
        if (actionBar != null) {
            actionBar.setDisplayHomeAsUpEnabled(true);
            actionBar.setDisplayShowHomeEnabled(true);
            actionBar.setDisplayShowTitleEnabled(true);
            actionBar.setDisplayUseLogoEnabled(false);
            actionBar.setHomeButtonEnabled(true);
        }`

**Comment by smidaharoun** [comment]
Could any one post the code on how to add the viewPager in a fragment
