### ISSUE TITLE
setOnClickListener on header does nothing

### ISSUE THREAD

**Issue by thatisazam** [florent37/MaterialViewPager#99]
Instead of using logo, I used custom header for my layout which contains a button. Unfortunately the onClick event does not invoked. The onClick only seems to invoke if I put the layout as logo but i prefer the header parallax than logo's

**Comment by gouravd** [comment]
Did you have any luck in this yet? I am trying to achieve the same thing

**Comment by thatisazam** [comment]
The workaround is to divide the static views into header and the controls (buttons etc.) into logo..the transition looks acceptable though

**Comment by florent37** [comment]
should be fix on the '1.1.0', can you try ?

sorry for this issue :'(
